### ISSUE TITLE
SonyLiv not working

### ISSUE THREAD

**Issue by MrSShiv** [Vikassm73/AjaykRepo#100]
SonyLiv episodes not playing. After logging by phone number, when tried to play any episodes then it's giving some subscrip error

**Comment by MrSShiv** [comment]
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/9593207/kodi.log)

**Comment by SJ22032003** [comment]
Yep, Voot also not working.

**Comment by Vikassm73** [comment]
Now check

**Comment by Nzzyme** [comment]
Still same issue. Just checked now. There is a SonyLiv add-on update that Kodi tries to update but fails everytime.

**Comment by Vikassm73** [comment]
Sorry, update was not copied at proper place. Now try to play.

**Comment by Nzzyme** [comment]
> Sorry, update was not copied at proper place. Now try to play.

Updated the add-on and it still gives an error upon playing any content. Can you please check?

**Comment by Vikassm73** [comment]
> > Sorry, update was not copied at proper place. Now try to play.
> 
> Updated the add-on and it still gives an error upon playing any content. Can you please check?

previously, was it working fine ?

Are you using valid subscription ? Try to put mobile number which is not valid subscription and play.

**Comment by Nzzyme** [comment]
> > > Sorry, update was not copied at proper place. Now try to play.
> > 
> > 
> > Updated the add-on and it still gives an error upon playing any content. Can you please check?
> 
> previously, was it working fine ?
> 
> Are you using valid subscription ? Try to put mobile number which is not valid subscription and play.

Yes, it was working until a week or so ago. I never used to login with phone number. Just used to watch the free content via your Kodi add-on (Ex: CID) and it worked earlier. But now keep getting an error when ever I try to play any free content too.

**Comment by Nzzyme** [comment]
> Previously, It was working without mobile number but now it is compulsory to enter mobile number. It will send OTP to your number. After you enter OTP, you should able to play free content. I have just tested it for Free and those are working fine.

Thanks for the update. Will try to login with phone number and check.

**Comment by akshayv73** [comment]
Premium content is not working in version 2.0.14 it says you need to subscribe when i already have subscription

**Comment by Vikassm73** [comment]
[plugin.video.sonyliv.zip](https://github.com/Vikassm73/AjaykRepo/files/9613033/plugin.video.sonyliv.zip)


Manually install above zip. Enable Debug logging. First clear log. On next move, it will ask to enter OTP. Proceed and try to play.  If failed, send me a debug log.

**Comment by akshayv73** [comment]
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/9615884/kodi.log)

**Comment by Vikassm73** [comment]
[plugin.video.sonyliv.zip](https://github.com/Vikassm73/AjaykRepo/files/9616066/plugin.video.sonyliv.zip)


Please try above zip and let me know the status

**Comment by akshayv73** [comment]
yes tried that zip and then i took the log

**Comment by Vikassm73** [comment]
This is new zip. modified after your log file

**Comment by akshayv73** [comment]
Yes working thank you so much
