### ISSUE TITLE
Zee5 showing Invalid Device ID

### ISSUE THREAD

**Issue by nsas02** [Vikassm73/AjaykRepo#101]
I've entered UN and Pwd correctly. When I try to play any video, it says DeviceID is invalid. Any help on this is appreciated.

**Comment by Vikassm73** [comment]
Please go through the closed issue on same topic.

**Comment by Daredevil1092** [comment]
> Please go through the closed issue on same topic.

Can you please make an addon for Disney+Hotstar?
