### ISSUE TITLE
Need a jio tv addon

### ISSUE THREAD

**Issue by ajdeshmane0007** [Vikassm73/AjaykRepo#103]
Recently botallen stopped there all services now its time 2 launch jio tv addon for kodi there is lot off users who use a jio tv on kodi i hope you will think about it and work great on it.... Jio movies also a best to make its also provide a lot off content for free

**Comment by Nzzyme** [comment]
+1 for this request.

@Vikassm73 Can you please consider making the following 2 add-ons for Jio:

- JioTV
- JioCinema

**Comment by Vikassm73** [comment]
JIO TV need valid subscription. No plan to work on this

**Comment by iamnewtogithubhelpme** [comment]
Jio tv with subscription is fine.  we can use our Jio number to access Jio tv for free.

**Comment by ksadda77** [comment]
> 
Jio TV addon from Botallen is working fine. Only thing is you should not enable ' Extra HD channels ' in settings.

**Comment by sachtech** [comment]
> 

default it's disabled, so still not working

**Comment by jamalfeb1** [comment]
Thanks

**Comment by pankajlohar22** [comment]
please add jiotv addon

**Comment by Sunil1142** [comment]
Jio tv not working in kodi

**Comment by sachtech** [comment]
it stopped woking again
