### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#106]

**Comment by Fjfjrixi** [comment]
Please make a hotstar and jio tv repository becase hotstar show error after play any tv show and jio tv automatically log out many times please give feature in mx player to change video quality

**Comment by Vikassm73** [comment]
JIO TV need valid subscription. No plan to work on this. For Hotstar, I will check code and then decide. 

To get access for different video format, you need to set "Input Stream adapative in Manual mode.

Setting Path  = Add-On - My Addon -  Videoplayer Inputstream - Inputsteam Adaptive - Configuration


![image](https://user-images.githubusercontent.com/41675437/192493353-95399792-d89e-4f8a-a483-0b9da59d8b39.png)

**Comment by Fjfjrixi** [comment]
Its not working in mx player
