### ISSUE TITLE
Issue of Sonyliv Repo

### ISSUE THREAD

**Issue by alternative-ultron** [Vikassm73/AjaykRepo#107]
When the update was not come I think it's version 2.0.15 , It's again the Same problem like 2.0.13 - All Free content doesn't play while actually it's logged in through mobile number. It's Required to Purchase Premium and want Subscription account. While that same Free content is playable on Sonyliv app and also as website. Please Do something, And keep it up for you work we will support you. 
![16642685425816953457942687347183](https://user-images.githubusercontent.com/79961866/192479700-84b081e2-db50-4449-9550-7efa814f1ec3.jpg)

**Comment by Vikassm73** [comment]
I have  checked again. There is no issue with free content. Just clear log and check again
