### ISSUE TITLE
Hotstar addon request

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#109]
Please make a hotstar add on for kodi botallen repo hotstar is showing error and video inputstream selection is not working in mx player to change video quality but this method works in all add on like voot zee5 sony liv but not working in mx player

**Comment by Vikassm73** [comment]
Manually download and install from https://github.com/Vikassm73/plugin.video.botallen.hotstar

I won't add this to my repository until "bottallen" rejects my pull request and doesn't make the necessary adjustments in his repository.

**Comment by Fjfjrixi** [comment]
Okk thanx

**Comment by AbhayF8** [comment]
Was working fine in the morning but now it's giving API error
See log (I am not logged in)
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/9706889/kodi.log)

**Comment by Vikassm73** [comment]
Yes, there is an issue. No valid solution found. Let's hope for the positive

**Comment by Vikassm73** [comment]
Correction done. If you face any issue just press "Log Out" from setting and try again. Let me know if you face any further issue

**Comment by Fjfjrixi** [comment]
How to install this hotstar addon

**Comment by Vikassm73** [comment]
![image](https://user-images.githubusercontent.com/41675437/200232419-49fbcaa0-c953-4fe1-977a-997df439fd5e.png)

**Comment by Vikassm73** [comment]
Please see above Download zip option.

**Comment by Fjfjrixi** [comment]
This zip file is not working please put this into your repository and update this add on or request from botallen for update and fix this error

**Comment by Vikassm73** [comment]
Not working means what? are you not able to install it? Or failed to play any content? please explain

**Comment by Fjfjrixi** [comment]
Content are not playing same error like botallen repository hotstar zip file please update and fix this problem 😫😫😫😫😫

**Comment by Fjfjrixi** [comment]
Waiting for yor reply sir

**Comment by Vikassm73** [comment]
[plugin.video.botallen.hotstar.zip](https://github.com/Vikassm73/AjaykRepo/files/10001427/plugin.video.botallen.hotstar.zip)


Download and install above zip

Enter settings and do logout.

After that try to play any content. Please send me the debug log if failed

**Comment by vikasvisking** [comment]
@Vikassm73 can we login and play ?
because on login popup after i enter my mobile no.
nothing happens

**Comment by Vikassm73** [comment]
Download above zip and install it (Just now updated). Logout first and login again

**Comment by Fjfjrixi** [comment]
its working perfectly thanx ☺☺

**Comment by MohanRVLK** [comment]
Hello Vikassm73,

If this development is still active, could you offer some help with login issues again? I get 404 error after entering mobile number and submitting.
