### ISSUE TITLE
SonyLiv 

### ISSUE THREAD

**Issue by nikhilk0** [Vikassm73/AjaykRepo#11]
Issues
- Some contents in some categories don't have thumbnails. e.g. 'Most Watched in Entertainment', 'Indian Idol Uncut Performances'.
- Also in the above-mentioned categories, on the website, the content has sub-heading which are more informative than the actual show name. But in addon only show name gets listed.
- Categories 'Watch In Your Language' and 'Popular TV Shows' are throwing errors when trying to access them.

Requests
- Include sports section. 
- Search option

Live channels are working fine. And all other content (which I tested) except premium movies is working fine. This addon is shaping up really well. Thanks for all the hard work.

**Comment by nikhilk0** [comment]
In the next update, can you add ['Live TV'](https://www.sonyliv.com/custompage/live-tv-532) section in the mainlist? It has all the live channels including sports channels in one section. This section will make access to live channels easier. I've already added it to my personal setup and it's working fine (except the last section from website). 
Also, if possible, change the fanart to [this](https://www.bizasialive.com/wp/wp-content/uploads/2020/05/899ec721-sonylivnew001-696x443.jpg.webp). The current fanart has the old logo.

**Comment by Vikassm73** [comment]
**New version of Sonyliv App updated**


> Issues
> 
> * Some contents in some categories don't have thumbnails. e.g. 'Most Watched in Entertainment', 'Indian Idol Uncut Performances'.
> * Also in the above-mentioned categories, on the website, the content has sub-heading which are more informative than the actual show name. But in addon only show name gets listed.

**Correction Done**

> * Categories 'Watch In Your Language' and 'Popular TV Shows' are throwing errors when trying to access them.
> 

**No solution found**


> Requests
> 
> * Include sports section.
> * Search option
> 

**Sport section added but most of the options are not working as they are for premium users. Search is not working properly so not added now **


> Live channels are working fine. And all other content (which I tested) except premium movies is working fine. This addon is shaping up really well. Thanks for all the hard work.

**New Section added**

**Comment by Vikassm73** [comment]
> In the next update, can you add ['Live TV'](https://www.sonyliv.com/custompage/live-tv-532) section in the mainlist? It has all the live channels including sports channels in one section. This section will make access to live channels easier. I've already added it to my personal setup and it's working fine (except the last section from website).
> Also, if possible, change the fanart to [this](https://www.bizasialive.com/wp/wp-content/uploads/2020/05/899ec721-sonylivnew001-696x443.jpg.webp). The current fanart has the old logo.


**New Section added**

Using same old Fanart as I have already used above mentioned image as  a thumbnail.

**Comment by nikhilk0** [comment]
Nice work with the changes. 
Few comments about the changes:
In line 535, add 'LIVE_SPORT' also. With this change, streams from 'Live Now' section from Sports menu should be playable.

The 'Euro Moments 24x7' live channel isn't working. On further digging I noticed that, as it's a free channel it is using normal vod stream instead of 'freeview' like the other live channels. Also, 'is_preview_enabled' in its json is false but for other live channels it's true. So, to make this channel work, maybe you can do:
```
if preview=true:
     play live
else:
     play stream
```
Although, I'm assuming that sonyliv does this to all their free live streams, I can't be sure about it as there are no other free live streams to check.

> Sport section added but most of the options are not working as they are for premium users. Search is not working properly so not added now

Do you have any idea why this happening? I'm asking because the videos such as highlights and clips are playable on the website   without premium but in kodi they return 403.

> Using same old Fanart as I have already used above mentioned image as a thumbnail.

I suggested that change because the sonyliv logo on the current fanart is years old and it doesn't match the current icon. Also, many other addons use similar icon and fanart if no alternative fanart is available (refer slyguy repo for some examples).

I'll update here if notice any other issues.

**Comment by nikhilk0** [comment]
When I tried playing live sports channels (all channels except Ten 1 and Ten 1 HD) when they were telecasting Euros live, they returned the same 403 error as highlights and clips. All other live channels worked fine.

This url was requested when Euros was Live on Six HD and returned 403

> https://sonydaime.akamaized.net/hls/live/2022318/MA5/serve.key?hdntl=exp=1625679067~acl=/*~id=62687800903515840659531706595657~data=hdntl~hmac=e07b79f10019a25200e3d24aec2a4fa272e6c3c841ded1140294f34d90786bc0&aka_me_session_id=AAAAAAAAAADb5OVgAAAAAFmdcjzPpzjrJyzum3LgZcwuX%2fZSxEIUPotlh5%2fWRFd9dzwLnQnlzpAXQQH04JJ1zwjfcmjVSy6z

And this is the url when the channel plays without any issues

>https://sony247channels.akamaized.net/hls/live/2020593/SONYSIXHD/hdntl=exp=1625711699~acl=%2f*~id=86936981777044151598185692693453~data=hdntl~hmac=c962195a970434506930e92208f7b36b1c2ed4605576c18465c6058778857e96/20210610T121939/master_3500/02916/master_3500_00099.ts

Thought it was interesting.

**Comment by Vikassm73** [comment]
They are replacing it with premium link while live sport events.

**Comment by nikhilk0** [comment]
Yeah, I noticed. When the stream is playing (no premium content is playing), 'is_encrypted' is false and there is no mention of drm. But when premium live content starts airing, they enable drm. 'is_encrypted' is true and a drm key gets listed in the apis. 

Sports content is also is drm encrypted. 

Won't it be possible to implement widevine drm within the addon? I mean the sports content isn't necessarily 'Premium'. It's just encrypted and inputstream adaptive has support for widevine drm.

**Comment by nikhilk0** [comment]
I managed to get the 'sonydaime' links, which were earlier giving 403 error, working by adding 'license_type' and 'license_key' properties. I have only tried them with cricket though and that too only for the stream from the 'Live Now' section (tv channel which was airing the match was still using 'sony247channels' url). Couldn't test for football matches due to late night hours. Will try to test for Euros tonight, if possible.

I also added the same properties for mpd links (I commented out the replace mpd to m3u8 line for testing) to test out the sports section. But I get `ERROR <general>: AddOnLog: inputstream.adaptive: Could not find protocol inside url - invalid` this error. Maybe I'm missing something in the license url.

**Comment by nikhilk0** [comment]
> The 'Euro Moments 24x7' live channel isn't working. On further digging I noticed that, as it's a free channel it is using normal vod stream instead of 'freeview' like the other live channels. Also, 'is_preview_enabled' in its json is false but for other live channels it's true. So, to make this channel work, maybe you can do:

```
if preview=true:
     play live
else:
     play stream
```

> Although, I'm assuming that sonyliv does this to all their free live streams, I can't be sure about it as there are no other free live streams to check.

Checked with Euro pre-game show which is also a free live stream and it's the same. 'is_preview_enabled' is false. It is also using normal vod stream instead of 'freepreview' stream.

> Couldn't test for football matches due to late night hours. Will try to test for Euros tonight, if possible.

It's working.

**Comment by Vikassm73** [comment]
> something

Will you share your code of license key here.
I am getting "Protocol Error" also in "Live Now" section

**Comment by Vikassm73** [comment]
> I managed to get the 'sonydaime' links, which were earlier giving 403 error, working by adding 'license_type' and 'license_key' properties. I have only tried them with cricket though and that too only for the stream from the 'Live Now' section (tv channel which was airing the match was still using 'sony247channels' url). Couldn't test for football matches due to late night hours. Will try to test for Euros tonight, if possible.
> 
> I also added the same properties for mpd links (I commented out the replace mpd to m3u8 line for testing) to test out the sports section. But I get `ERROR <general>: AddOnLog: inputstream.adaptive: Could not find protocol inside url - invalid` this error. Maybe I'm missing something in the license url.

Will you share your code of license key here.
I am getting "Protocol Error" also in "Live Now" section

**Comment by nikhilk0** [comment]
I've made some changes to make 'Live Now' section and free live channels (Euro 24x7 channel was there earlier but now it's gone) working. But I couldn't get the Sports section working and I'm getting the mentioned error. I would've created a PR had the addons uploaded normally instead of zips. Hope this is helpful and you're able to improve upon this. 
Also, there are some open issues regarding that issue on ISA repo if you want to check further.
[main.zip](https://github.com/Vikassm73/AjaykRepo/files/6836465/main.zip)

**Comment by Vikassm73** [comment]
> I've made some changes to make 'Live Now' section and free live channels (Euro 24x7 channel was there earlier but now it's gone) working. But I couldn't get the Sports section working and I'm getting the mentioned error. I would've created a PR had the addons uploaded normally instead of zips. Hope this is helpful and you're able to improve upon this.
> Also, there are some open issues regarding that issue on ISA repo if you want to check further.
> [main.zip](https://github.com/Vikassm73/AjaykRepo/files/6836465/main.zip)

Just not got it working (Live Now Section). Anyway thanks

**Comment by nikhilk0** [comment]
> > I've made some changes to make 'Live Now' section and free live channels (Euro 24x7 channel was there earlier but now it's gone) working. But I couldn't get the Sports section working and I'm getting the mentioned error. I would've created a PR had the addons uploaded normally instead of zips. Hope this is helpful and you're able to improve upon this.
> > Also, there are some open issues regarding that issue on ISA repo if you want to check further.
> > [main.zip](https://github.com/Vikassm73/AjaykRepo/files/6836465/main.zip)
> 
> Just now got it working (Live Now Section). Anyway thanks. Still working on other issues.
> 
> i.e. (checked your code, you can not pass same stream url as a license key. It is different. I am surprised how still it is working. You will get to see this in the next version)

TBH I was surprised as well. For live streams, they're serving serve.key via stream url (at least that's what I observed). For drm-enabled mpd streams (sports clips & highlights), you can see the license url is different. Also, what I was trying was more of a casual hack than an actual fix. I hope you'll provide an actual fix in upcoming versions.
