### ISSUE TITLE
SONY LIV

### ISSUE THREAD

**Issue by deiamo** [Vikassm73/AjaykRepo#110]
With the Sony Liv repository being updated to V 2.0.15, unable to access past episodes on SET and other SET channels, this was possible in the repository version 2.1.1 , how do i resolve this, as, when i added the Ajay K repository it got automatically updated to the latest version

**Comment by Fjfjrixi** [comment]
Sign in again

**Comment by deiamo** [comment]
> Sign in again.............. i did so several times ... message received
Playback failed
One or more items failed to play. Check the log for more info about this message

**Comment by Vikassm73** [comment]
Are you using Premium Version or Free?

Do "Clear Cache". When we proceed, it will ask for OTP. Once done, it should work.

**Comment by deiamo** [comment]
I am using the file AKAY K repository ....... was working earlier, but
after the auto update this has gone awry , have cleared cache several
times, rather whenever i see any programe for a long time on exit i always
clear the cache

**Comment by Vikassm73** [comment]
Do you have valid subscription of Sonyliv?

**Comment by deiamo** [comment]
NO
