### ISSUE TITLE
Voot video size resolution is not 1080p?

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#111]
To be honest I am not very sure about this but I watch voot a lot and for some reason when I was watching shark tank, the resolution shows as 540p. But I will be frank, I don't think it is so low so not sure if kodi reporting it wrong. Pic is attached. 
But other wise too, most stuff is limited to 720p it seems.

![image](https://user-images.githubusercontent.com/85625460/193981919-d4bfdcf5-0b74-4e5a-90da-dd8b08612452.jpeg)

**Comment by Vikassm73** [comment]
Yes, premium content are not in HD. Premium HD content use a encryption which is not possible to decode hence used low resolution. However, Non premium content are in HD.

**Comment by iamnewtogithubhelpme** [comment]
Thanks a lot for the clarification.
