### ISSUE TITLE
Cannot play premium content from France on Zee5

### ISSUE THREAD

**Issue by atallur** [Vikassm73/AjaykRepo#112]
Hello,
Thanks a lot for your work!
I am in France and have recently subscribed to a Zee5 premium account.
In Chrome on my PC, it works perfectly, I am able to view premium content (movies) without any VPN, which is a good surprise.

As I use Kodi on a Raspberry Pi (OSMC), I searched for extensions for Zee5 and installed yours, version 2.1.14.
I could make it work, with my login / password, and for the DeviceID used the guestToken copied from Chrome on my PC.
It works perfectly for viewing live TV (non premium content, like Zee News, WION, etc.)
However, I am not able to view any movie.
I also tried the version you have posted in issue #83, with no improvement.

I have enabled the debug log files as advised in issue #73.
Log file show that an error 403 is received when trying to get Widevine license for the content.
Below is an excerpt

```
2022-10-29 18:04:12.851 T:8906    ERROR <general>: CCurlFile::Open failed with code 403 for https://spapi.zee5.com/widevine/getLicense:
                                                   {"errorcode":371000005,"errormsg":"Widevine license request failed >> Verified media path cannot be verified","errorid":"141726e3-9b0f-41ab-aa91-d8ea9bf4750b"}
2022-10-29 18:04:12.851 T:8906    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
```

After this failure to get license, we see that Kodi anyway tries to play the stream without success, and after a few seconds, displays sad face smiley and restarts.

Please find full debug log here: https://paste.kodi.tv/obikelufig.kodi

Is https://spapi.zee5.com/widevine/getLicense supposed to work outside India? 
May be not, and it would explain the issue.

Thanks a lot for your help.

Anand

**Comment by atallur** [comment]
Some more details.
I have verified with dev tools in Chrome the http requests that happen when playing a movie in the browser.
The request of type POST to https://spapi.zee5.com/widevine/getLicense is well present and works.
So I guess may be the issue is the movie token which is passed to this query. May be an issue of country code.
I will perform more investigations.

**Comment by Vikassm73** [comment]
Till date there is no solution for this error "Verified media path cannot be verified"
The same may work under Linux platform
try in Libreelec or osmc

**Comment by atallur** [comment]
Thanks for your answer.
I am already using OSMC.
Looking more closely in log at POST query sent to  https://spapi.zee5.com/widevine/getLicense, I wonder if code 403 received from the server could not simply be due to the "user-agent" property passed in query header, which is the following:
HEADER_OUT: user-agent: Kodi/19.4 (X11; Linux armv7) Linux/2022.09-1 App_Bitness/32 Version/19.4
Will try to change this and give you feedback.
