### ISSUE TITLE
Issues with SonyLIV and Zee5

### ISSUE THREAD

**Issue by Daredevil1092** [Vikassm73/AjaykRepo#113]
These 2 addons were used to work pretty fine but I'm facing some issue past a couple of weeks. Please help!!

![Capture](https://user-images.githubusercontent.com/112254137/201271756-0c318895-0448-487b-92b6-796a897b0cdd.PNG)

![sdf](https://user-images.githubusercontent.com/112254137/201271758-381a519d-c0e2-423b-8132-5d4645c83c2a.PNG)

**Comment by Vikassm73** [comment]
regarding device ID, just go through the closed issue of zee5.

Sonyliv is working fine.

**Comment by Vikassm73** [comment]
Try new updated zee addon. In case of sonyliv, just clear log and try again
