### ISSUE TITLE
Zee5 login issue 

### ISSUE THREAD

**Issue by ksadda77** [Vikassm73/AjaykRepo#116]
Not able to login to Zee5 addon though I have valid subscription. Pls help.

**Comment by Vikassm73** [comment]
Need exact error message.

**Comment by ksadda77** [comment]
Hi, while entering login details, I am not getting any error. While trying
to play premium content like live channels, getting error like 'This
content is not supported in your country' & also one or more items failed
to play error. I am from India only. Zee5 app separately is working fine
with same login details. Pls help.

Regards,
Kiran

**Comment by Vikassm73** [comment]
[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/10072723/plugin.video.zee5.zip)

Install above zip. enabled a debug log and send me the log after playback failed on vikassm73@gmail.com.
Give me details of the content which you are playing.

**Comment by ksadda77** [comment]
Thank you so much brother. It worked. Can you pls provide addon link for
Hotstar 1.2.1?

Regards,
Kiran
