### ISSUE TITLE
Zee5 log in failed

### ISSUE THREAD

**Issue by Ashubnx** [Vikassm73/AjaykRepo#123]
Is there any option to log in

**Comment by Vikassm73** [comment]
Before starting an addon. Right click and enter into the setting. There is an option to Enter Email/Mobile and password. You can keep password blank if you are using OTP based login.

**Comment by Ashubnx** [comment]
Tried it.. now it's showing zee5 error, check the log for more information

**Comment by Vikassm73** [comment]
First enable the debug. Start zee5 app. First Press on clear log. It will ask the OTP. Enter the OTP. If error occurs, send me a debug log on vikassm73@gmail.com

**Comment by Ashubnx** [comment]
Showing this error

**Comment by Vikassm73** [comment]
Go in setting, choose device ID D3

**Comment by Ashubnx** [comment]
Again Playback failed one or more items failed to play check the log for more information 😅

**Comment by Vikassm73** [comment]
No error message on this screen. May be on next. If possible send me kodi.log

**Comment by Vikassm73** [comment]
IT's VMP issue which can not be solved in windows system. Read more about this

https://github.com/xbmc/inputstream.adaptive/wiki/Verified-Media-Path-%28VMP%29

**Comment by smcoder0707** [comment]
> IT's VMP issue which can not be solved in windows system. Read more about this
> 
> https://github.com/xbmc/inputstream.adaptive/wiki/Verified-Media-Path-%28VMP%29

Does this mean Zee5 won't work at all or just won't work for premium content only? Probably you should write this in big bold letters on the Readme, As I can there are tons of Zee5 Issue threads getting made.

**Comment by Vikassm73** [comment]
This won't work for specific device. (Like Windows)  It works perfectly under Linux As well as valid Android device.

**Comment by Ashubnx** [comment]
Playback failed check the log for more information for sony liv.

**Comment by Vikassm73** [comment]
don't find any error. Send me a debug log. Also, keep separate thread for sonyliv and zee5.
