### ISSUE TITLE
SonyLiv OTP - Invalid Phone number

### ISSUE THREAD

**Issue by xtreamjava** [Vikassm73/AjaykRepo#127]
Hi

Sonyliv OTP login not working. Tried to clear cache and got error - Invalid Phone Number.

I have attached the logs below.

https://paste.kodi.tv/awixopagiz.kodi

**Comment by Vikassm73** [comment]
Was it working fine previously?
Tested here. It is working fine. Please check the phone number in settings again.

**Comment by xtreamjava** [comment]
This is the fist time I'm trying this addon. I have tested with and without +91 as well, But I'm not getting any window to enter OTP and On clear cache its throwing Invalid phone Number error. 

Sonyliv app and web works fine with the same phone number.

**Comment by Vikassm73** [comment]
You have to enter 10 digit phone number only

![image](https://user-images.githubusercontent.com/41675437/207227207-35db2ca4-cf5c-4ad3-bb88-f5522f123b2c.png)

**Comment by xtreamjava** [comment]
I have entered 10 digit Mobile number. I don't get any OTP windows. And after clear cache i get the following screen.
![Screenshot 2022-12-13 21-51-13](https://user-images.githubusercontent.com/92907712/207299028-ac09359e-e624-4e37-835b-005dfc84b198.png)

and when i clicked on a episode i get the above error + check logs error
![Screenshot 2022-12-13 21-56-35](https://user-images.githubusercontent.com/92907712/207299788-1bbba832-6988-45ae-bbcf-eeb96a3190eb.png)

**Comment by Vikassm73** [comment]
[plugin.video.sonyliv.zip](https://github.com/Vikassm73/AjaykRepo/files/10224231/plugin.video.sonyliv.zip)


Manually install above zip and send a debug log file on vikassm73@gmail.com

**Comment by xtreamjava** [comment]
Phone number's first three digits are 628

**Comment by Vikassm73** [comment]
[plugin.video.sonyliv.zip](https://github.com/Vikassm73/AjaykRepo/files/10233575/plugin.video.sonyliv.zip)


Install above zip and try

**Comment by xtreamjava** [comment]
Sorry, I got little side tracked. I'll test on Monday

**Comment by snowdog05** [comment]
I tried above zip, It doesn't worked for me, showing same error. I tried in some shark tank india episodes which dont require login to watch.

**Comment by Vikassm73** [comment]
You just enter your mobile even for the Free content. Enter OTP and try to play

**Comment by snowdog05** [comment]
Cleared Kodi's app cache, reentered mobile number and OTP, Now it's working.
Thanks a lot!

**Comment by xtreamjava** [comment]
Hi, Sorry I was busy and didn't had a change to respond. I did get the OTP prompt with the new zip file, but it is still throwing error. I'm going to try on another android STB, and I'll report back with the log file.

**Comment by Vikassm73** [comment]
Already push to main addon. Let me know what issue you are facing with log file
