### ISSUE TITLE
Zee5 addon issue

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#128]
Content are not playing in zee5 login error and not login success otp are not working please update app and fix this problem

**Comment by Vikassm73** [comment]
[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/10224497/plugin.video.zee5.zip)


I have tested and it is working fine. Manually update above zip and do Clear Log. If it does not ask for OTP, send me a debug log on vikassm73@gmail.com

**Comment by snowdog05** [comment]
Hello,
I have tried zee5 addon which is in repository and the above you provided separately. I tried it on phone, tab and TV and i can confirm that zee5 addon is not working.
Sometimes it throws Zee5 addon error, sometimes playback failed error.
Please check.

**Comment by Vikassm73** [comment]
if you got 403 error then nothing can be done otherwise Zee5 is working fine .

**Comment by ksadda77** [comment]
> [plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/10224497/plugin.video.zee5.zip)
> 
> I have tested and it is working fine. Manually update above zip and do Clear Log. If it does not ask for OTP, send me a debug log on [vikassm73@gmail.com](mailto:vikassm73@gmail.com)

Zee5 is asking OTP every time we start Kodi. Can you pls help?
Regards,
Kiran

**Comment by snowdog05** [comment]
Ok, It seems error with some content. I tried free live tv channels and some movie trailers and marathi / hindi next episode trailers and it is working. but when i try to play hindi / marathi episodes, it shows playback failed error.

**Comment by PrasannaChatufale** [comment]
On web interface following plays perfectly https://www.zee5.com/music-videos/details/nasha-game-paisa-ladki--deepanse-garge-sezal-sharma/0-0-66449
Through Kodi on same mobile gives error "One or more items failed to play"
Also in web interface it is not asking OTP unless and until logged out whereas in Kodi it is asking for OTP each time it is started. Pls check.

**Comment by Vikassm73** [comment]
Have you tested with new update? New update does not ask OTP every time. Otherwise, it is better to enter you email and password to avoid OTP.
For stream working, I will add stream selection. You will able to select stream which is working

**Comment by PrasannaChatufale** [comment]
1. On mobile I have updated through Versions got alert addon updated. Now
not asking for OTP. On tv I will try later.
2. There is mismatch between Kodi ZEE5 addon and ZEE5 web interface. The
menus not matching. Eg On Kodi ZEE5 there is "Top 10 on ZEE5 Bangla" under
premium but on ZEE5 web interface it is not traceable under premium.

Thanks and Regards,
Prasanna

**Comment by Vikassm73** [comment]
Do clear log. It will ask OTP. Menu items go on changing. It depends on language settings.

**Comment by PrasannaChatufale** [comment]
In event log nothing appears. From where to clear log? Whether to clear
cache or not?

Regards

Prasanna

**Comment by Vikassm73** [comment]
Sorry It's "Clear Cache"
