### ISSUE TITLE
SonlyLiv stucks / exits durring advertising breaks.

### ISSUE THREAD

**Issue by ganesh-user** [Vikassm73/AjaykRepo#135]
H96 Android Box,
Kodi Version- 19.3
sonyliv-2.0.15
From last 7-8 days noticing problem that  SonyLiv stucks / exits abruptly during advertise breaks. Guess update needed for SonlyLiv ?

**Comment by Vikassm73** [comment]
Let me know where you face this problem. In Live TV?

**Comment by ganesh-user** [comment]
Currently I have observed this problem while playing live content.

**Comment by iamnewtogithubhelpme** [comment]
I concur. Have seen this issue where during an ad, stream gets stuck or completely exits. Device is Onida Fire tv edition tv.

**Comment by virubhai22** [comment]
can i use my sony liv mobile subscription in this add on

**Comment by snowdog05** [comment]
I have another problem with this addon. some shows are not visible or not playing. For e,g, I am trying to play shark tank unseen pitches, it doesn't work. But on website it plays normally. sometimes addon takes too much time to load.

**Comment by Fjfjrixi** [comment]
> Let me know where you face this problem. In Live TV?

Sony liv content are not playing please update and fix

**Comment by ganesh-user** [comment]
> > Let me know where you face this problem. In Live TV?
> 
> Sony liv content are not playing please update and fix

H96 Android Box, Kodi Version- 19.3
To me Sonyliv is working as usual without any problem. Except the current problem of stucking / exiting during advertising breaks.
