### ISSUE TITLE
Jio Tv Addon (Botallen stopped working)

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#136]
The Botallen repo and addon is no longer being maintained and since last 2 days, Jio tv has almost stopped working on Kodi. 
I understand someone had asked you before about Jio tv addon and you had mentioned that there is one that works. 
Well that seems to be not the case so it would be great if you can create a Jio tv addon.

**Comment by jamalfeb1** [comment]
Can any one help how to install from zip file which was posted by vikassm73/AjaykRepo

**Comment by shri1990** [comment]
Yes botallen JioTv has stopped working almost 80%..  @Vikassm73 request you to please check if possible to clone and manage the same repo... 
We all respect and appreciate your time and efforts..

**Comment by ganesh-user** [comment]
> Can any one help how to install from zip file which was posted by vikassm73/AjaykRepo
First download the file in pen drive. Connect the pen drive to device. And then there is option in kodi to install from zip file, browser storage, locate your file and install.

**Comment by ganesh-user** [comment]
Replying to jamalfeb1 comment > Can any one help how to install from zip file which was posted by vikassm73/AjaykRepo

First download the file in pen drive. Connect the pen drive to device. And then there is option in kodi to install from zip file, browser storage, locate your file and install.
