### ISSUE TITLE
Add New Add on JioCinema

### ISSUE THREAD

**Issue by bumehta17031947** [Vikassm73/AjaykRepo#137]
please add JIOCINEMA as addon in your repository,

**Comment by Vikassm73** [comment]
The shows on JIOCINEMA are incomplete (Specially shows like Big Boss, Splitsvilla etc.). Films are ok. It seems pointless to me to waste time on this.

**Comment by bumehta17031947** [comment]
Please add Jio Cinema as it only have Gujarati movies and large community of Gujarat is missing , Pl spend your valuable time and help the community

**Comment by bumehta17031947** [comment]
Please add Jio Cinema as it only have Gujarati movies and large community of Gujarat is missing , Pl spend your valuable time and help the community

**Comment by Vikassm73** [comment]
install and try below addon. Only movies are working
[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10424272/plugin.video.jiocinema.zip)

**Comment by bumehta17031947** [comment]
Thank you Very much , yes movie section is working

**Comment by bumehta17031947** [comment]
Jio cinema require log in which you attached with hotstar addons , where as it is complimentary from Reliance jio number , request to amend the loin with JioTV addons instead Disney +hotstar  because it is not necessary that all jio mobile user have the subscription, kindly correct this at the earliest, Regards

**Comment by bumehta17031947** [comment]
JIO CINEMA addon require to login which can be done by adding Disney+Hotstar add on to Jio Cinema, Jio Tv and Jio Cinema are both complimentary to JIO Mobile user by Reliance. Most Users do not Subscribe Disney+Hotstar as a result log in fail resulting JIO Cinema movie files does not open, Requesting to create builtin login method or club with JIO TV add on , Kindly add this at the earliest. Thanks in advance for your support to KODI community, Regards

**Comment by Vikassm73** [comment]
Only Movie section was working in the addon which I have uploaded here. In Repo, I have uploaded complete addon without login feature.

**Comment by bumehta17031947** [comment]
I reinstalled the JIO CINEMA from your add on , selected Gujarati Movie, Movie Name is Chabutaro second on first page or Fakt Mahilao Mate you can check  , it says valid subscription required , that is log in with Jio mobile number , On Jjiocinema.com when logged in, it plays hence i request you to please add login method either with JioTv add on or independent , so that viewers can enter their jiomobile number and can watch all movies without any interruption,I request your help please, Regards

**Comment by Vikassm73** [comment]
Login feature added. Please use another running thread to download the updated add-on. Only there can you add more comments. I'm ending this thread.
