### ISSUE TITLE
Zee5 Invalid Device ID

### ISSUE THREAD

**Issue by ganesh-user** [Vikassm73/AjaykRepo#139]
H96 Android Box,
Kodi Version- 19.3
Zee5-2.1.16

I know earlier it has been mentioned to search the solution in closed issue of Zee5. Accordingly I have searched all the closed issues but unable to find solution for Zee5 Invalid Device ID for Android Box Kodi. And hence opening this new issue. Any help appreciated.

**Comment by Vikassm73** [comment]
read this

https://github.com/Vikassm73/AjaykRepo/issues/61#issuecomment-1127305648

**Comment by ganesh-user** [comment]
I have earlier read this, but unable to find any matching / workable solution. Am I missing something to read ?

**Comment by ganesh-user** [comment]
I have earlier read this, but unable to find any matching / workable solution. I dont understand what to type in device ID option provided. Am I missing something to read ?

**Comment by ganesh-user** [comment]
I have earlier read this, but unable to find any matching / workable solution. I dont understand what to type in device ID option provided. Regarding Chrome browser developer tools, Android chrome browser doesn't have that option. Am I missing something to read ?

**Comment by Vikassm73** [comment]
Instead of android, you can also get it from your PC and use the same

**Comment by Vikassm73** [comment]
You don't need to add quotation mark. Actually it should have work without adding device ID.

Try following.

Install Kiwi Browser in Android. You will get Development tools option. Follow the same procedure.

**Comment by ganesh-user** [comment]
OK, with Kiwi Browser in Android found out device ID (Surprisingly it was different then on computer browser). With that added, Now I can play free content. But surpassingly DD National HD gives error "Invalid ID" (is this different then  "Invalid Device ID"?)
While ZEE TV HD says "Subscription required)

**Comment by ganesh-user** [comment]
OK, with Kiwi Browser in Android found out device ID (Surprisingly it was different then on computer browser). With that added, Now I can play free content. But surprisingly DD National HD gives error "Invalid ID" (is this different then "Invalid Device ID"?)
While ZEE TV HD says "Subscription required", I can Understand "Subscription required", since I am yet to subscribe. But unable to understand DD National HD error "Invalid ID"

**Comment by Vikassm73** [comment]
Don't find DD National In Live Channels. Please specify the path.

This error has nothing to do with Device ID. I will check this.

**Comment by ganesh-user** [comment]
Actually it seems like there is no path to DD National, or any DD channel. You can find it in putting "DD National" in Search option tab in bottom on home page.
Also update- This "Invalid ID" error is not just with DD National, but with all the DD Channels. I just checked this today. There are around 15 DD channels. What makes Zee5 important is no OTT platform has DD channels except Zee5. Jio has but it doesn't work on Kodi.

**Comment by Vikassm73** [comment]
Correction done for DD search

**Comment by ganesh-user** [comment]
OK. You mean you have done correction in Zee5 add-on ? But on github code page, I still see older zee5 version 2.1.16. Sorry I didnt understand what you mean.

**Comment by adityapv** [comment]
> OK. You mean you have done correction in Zee5 add-on ? But on github code page, I still see older zee5 version 2.1.16. Sorry I didnt understand what you mean.

@Vikassm73 has updated both zee5 and voot plugins 3hrs ago. DD channels are working fine now. You can manually download the latest zips from the github repository as the update is not yet available in addons update section in kodi.

**Comment by ganesh-user** [comment]
OK, I found zee5 version 2.1.18 on file page and updated it in my android box kodi. Now all DD channels are working fine. Just one question. It is not possible to find DD channels in some tab, eg. Live Tv tab, etc. Or we always need to search it in a search tab to Play it. ? @Vikassm73 I appreciate the work you are doing. As many suggested in other threads, I too would like to contribute towards donation. I think you should have one support platform for contributors. Thanks.

**Comment by adityapv** [comment]
> OK, I found zee5 version 2.1.18 on file page and updated it in my android box kodi. Now all DD channels are working fine. Just one question. It is not possible to find DD channels in some tab, eg. Live Tv tab, etc. Or we always need to search it in a search tab to Play it. ? @Vikassm73 I appreciate the work you are doing. As many suggested in other threads, I too would like to contribute towards donation. I think you should have one support platform for contributors. Thanks. 

You can add the channel once found in search in favourites (using context menu by long pressing on the channel) and then access it directly from Favourites section. You can also use OrderFavorites plugin to organize the favorites.

**Comment by Vikassm73** [comment]
zee5 updated. You will get all DD Channels in Live

**Comment by adityapv** [comment]
> zee5 updated. You will get all DD Channels in Live

Thanks a lot @Vikassm73 , I tried the new version of the plugin and now I can see dd channels and devotional channels in live tv section, however, while playing any channel now, I am facing 'Error in entitlementHelper' issue. Could you please look into the same?

**Comment by Vikassm73** [comment]
On web also it is not working. So need to wait until the issue is fixed.

**Comment by Vikassm73** [comment]
Now working
