### ISSUE TITLE
Botallen Jio TV plugin issue

### ISSUE THREAD

**Issue by Jaisoni23** [Vikassm73/AjaykRepo#141]
Recently botallen stopped the services now its time 2 launch jio tv addon for kodi there is lot off users who use a jio tv on kodi, please if you can fix the bug on botallen repository or crate a new one for jio tv.

**Comment by Anonymo3601a** [comment]
Please create one or fix the old one i am also using it from last 2 year but now it stopped working

**Comment by snowdog05** [comment]
Try this solution for Jio Tv addon and let us know if this works or not
https://github.com/botallen/repository.botallen/issues/344

**Comment by Jaisoni23** [comment]
Thank you for your response.
I've tried this few hours back and it's working fine.

**Comment by Animesh-FS** [comment]
@Vikassm73 From today, Again this problem is coming, no channels are working 
Kindly please update once you have solution

**Comment by vjviji** [comment]
@Vikassm73 same issue reoccurring again. Jiotv is no more working with kodi app. Could you please advise ?
