### ISSUE TITLE
Channel Request

### ISSUE THREAD

**Issue by adityapv** [Vikassm73/AjaykRepo#142]
@Vikassm73 Really appreciate the work you have been doing. 
Could you please add Vh1, MTV and sports18 channels in voot plugin? Also, if possible please add other Colors channels like Colors Gujarati Cinema, Colors Cineplex Superhits, Colors Cineplex Bollywood etc. 
Also, would really like to donate for the awesome work that you have done for many of us.

**Comment by Vikassm73** [comment]
Some Channels added. Colors Cineplex Superhits, you will find under movies section

**Comment by adityapv** [comment]
Thanks a lot @Vikassm73 . Really appreciate!

Sorry to bother you again, but there are some zee5 channels (DD channels and some devotional channels)  I was able to search DD channels, however, when I tried to play, it throws 'Invalid Id' error. Could you please add these channels under live tv if possible in your spare time?

Thanks a lot for your time and efforts!
