### ISSUE TITLE
Addon Request 

### ISSUE THREAD

**Issue by MKD1995** [Vikassm73/AjaykRepo#143]
Can you plz make a addon for Vi movies & tv

also there is some issue with Sony LIV addon like sometimes in commercial break it randomly exits and also sometimes random sonyliv adds pops up and can u add non hd Sony sab?

**Comment by Vikassm73** [comment]
Currently, There will be no new add-on. 

Live Sonyliv Channels, Issue is from there side so nothing can be done. About Sab, I will check

**Comment by virubhai22** [comment]
can i use my sony liv mobile subscription in this add on

**Comment by ganesh-user** [comment]
> can i use my sony liv mobile subscription in this add on

Yes you can use mobile subscription in this add on.

**Comment by ashish20092009** [comment]
Hiw to add this repo in kodi. Plz help me with it

**Comment by ganesh-user** [comment]
> Hiw to add this repo in kodi. Plz help me with it

download repo zip file in pen drive connect pen drive to device, go to kodi> settings > add on > install from zip > locate your zip file and install repo. After installing repo, go to add on and then install from repo. Here you can install which ever add-on you want to install from repo.
