### ISSUE TITLE
hotstar subscription

### ISSUE THREAD

**Issue by virubhai22** [Vikassm73/AjaykRepo#144]
Does anyone know if I will lose my Disney plus hotstar 1 year mobile plan if I port my VI sim to JIO?

**Comment by snowdog05** [comment]
I think no, because hotstar only demands valid mobile number not it's carrier. If you got your hotstar subscription with VI recharge, confirm it with VI customer care.

**Comment by virubhai22** [comment]
Has anyone ported before, his Hotstar plan remained the same ?
