### ISSUE TITLE
Zee5 Movies not working

### ISSUE THREAD

**Issue by ganesh-user** [Vikassm73/AjaykRepo#145]
H96 Android Box,
Kodi Version- 19.3
Zee5-2.1.19

I have valid subscription of Zee5 and I can watch all the live channels including movei channels, all the old TV shows episodes. But unable to play movies from Movies tab (which we can watch from start to finish any time, for eg. The Kashmir files.) Getting error "One or More item failed to play. check log for more information" I have also attached the screenshots of error log.[
![1](https://user-images.githubusercontent.com/99388090/211287452-47445786-ce31-415e-987e-10ed0e2815e4.jpeg)
![2](https://user-images.githubusercontent.com/99388090/211287493-1d22d4ac-8dc2-446f-996e-84a5b22f7241.jpeg)
](url)
Any solution ?

**Comment by Vikassm73** [comment]
was it working previously on this machine or first time you are trying?

**Comment by ganesh-user** [comment]
Update - After updating Zee5 addon to version-2.1.20, now not getting error "One or More item failed to play. check log for more information" instead the loading animation in the center keeps on circulating forever and the movie doesn't load.
