### ISSUE TITLE
Account Banned Issue

### ISSUE THREAD

**Issue by adityapv** [Vikassm73/AjaykRepo#146]
Hi @Vikassm73, I am trying to play premium channels with my subscription, however, I am receiving 'Account Banned' error.

Another thing I noticed is zee5 is sending  OTP over email instead of allowing to enter password during login. Maybe they have changed the login mechanism. Could you please check into this in your free time?

**Comment by Vikassm73** [comment]
If you use mobile number, it will send OTP. It's better to mail zee5 support. Provide your email ID and ask for a password. Regarding "Account Banned", Check the same on web site. May be you can talk to support and get it removed.

**Comment by nabakumarchow** [comment]
Same problem

**Comment by snowdog05** [comment]
Facing same issue, I am using add on without login, trying to play free content, still showing me same error.

**Comment by nabakumarchow** [comment]
Yes,i also tried the same

**Comment by adityapv** [comment]
My Issue got resolved when I typed 'D3' in DeviceID (Manual Entry) in addon settings.

**Comment by nabakumarchow** [comment]
How?

**Comment by snowdog05** [comment]
By Changing Device ID (Manual Entry) to 'D3' gave me 'Invalid Token' Message. However I changed Device ID to 'D1' and it worked. Thanks!

**Comment by nabakumarchow** [comment]
Where to change the device id

**Comment by adityapv** [comment]
Go to the settings of the addon, under General category, you will find Device ID (Manual Entry) option, enter D1 to D4 and check whichever works for you. For me D3 worked.

**Comment by nabakumarchow** [comment]
Showing token invalid

**Comment by Vikassm73** [comment]
Added a new version. Manual entry is no longer necessary.

**Comment by snowdog05** [comment]
installed plugin.video.zee5-2.1.20, cleared Device ID (Manual Entry) from setting.
It Worked! Thanks a lot!

**Comment by nabakumarchow** [comment]
Zee5 and sony liv both not working now
