### ISSUE TITLE
Hotstar sports

### ISSUE THREAD

**Issue by nabakumarchow** [Vikassm73/AjaykRepo#147]
Is there anything in kodi to watch hotstar sports without subscription

**Comment by Vikassm73** [comment]
No, it is not possible

**Comment by nabakumarchow** [comment]
Is there no way to watch star channels?

**Comment by MKD1995** [comment]
When I started using botallen Disney+hotstar in 2021 addon star channels used to work without subscription

**Comment by Vikassm73** [comment]
There may have been bugs, which have been fixed.

**Comment by nabakumarchow** [comment]
Is there any way to watch tataplay app without recharge
