### ISSUE TITLE
Jio cinema

### ISSUE THREAD

**Issue by LoCo8472** [Vikassm73/AjaykRepo#150]
installtion failed

**Comment by Vikassm73** [comment]
Try again

**Comment by LoCo8472** [comment]
![Untitled](https://user-images.githubusercontent.com/122518831/213129865-458b11fb-3857-438e-b7b4-c11a57f2b35a.jpg)

**Comment by LoCo8472** [comment]
also hotstar login issue how to login on hotstar

**Comment by Vikassm73** [comment]
There is no issue in both, Jiocinema and Hotstar. Hope you are using it from India only....

**Comment by LoCo8472** [comment]
i live in india brother 
also hotstar api error when i login

**Comment by Vikassm73** [comment]
![image](https://user-images.githubusercontent.com/41675437/213135966-2bc4ef81-56b1-4cba-b334-d56db58e6322.png)

**Comment by Vikassm73** [comment]
Set Playback quality to "Auto" and test again.

**Comment by LoCo8472** [comment]
okk working fine now i am using persol vpn thats y getting problme
