### ISSUE TITLE
Jio Cinema Audio issue 

### ISSUE THREAD

**Issue by Varun23102002** [Vikassm73/AjaykRepo#152]
Hey bro
There is issue while using audio stream sometimes goes or sometime high base buffering volume

**Comment by Vikassm73** [comment]
HD stream in Jio Cinema has an issue. Only below HD stream are working. About audio need further testing.

**Comment by Varun23102002** [comment]
Thanks bro for reply and your hard work
Please if you have telegram channel or any other apk group please share the
link.
Hope Audio Issue fix soon 🤗.

**Comment by snowdog05** [comment]
Hi bro, Thanks for Jio Cinema add-on. Great Work! If HD stream issue solved, it will be cherry on cake!
I noticed some lag while browsing in this add-on. for e.g.. movies menu takes some time to load, if you play any movie, it takes some time to play.
Thanks!

**Comment by Vikassm73** [comment]
Manually update below addon. Check login feature. If failed, send me a debug log

[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10463511/plugin.video.jiocinema.zip)

**Comment by Varun23102002** [comment]
Bro login successful but content not playing nothing even movies also

**Comment by Vikassm73** [comment]
logout and login again. and send me a debug log

**Comment by bumehta17031947** [comment]
Updated JioCinema with given file of update version, it shows login when logged in with otp, after that when opened movie it shows subscription error, like your Sonyliv  addon login number is displayed all the time but here it does not display number means JIOCINEMA does not logged in, When JIOTV is logged in it  displays **log in Success** and all channels can be viewed where as in JioCinema only free content is being viewed though it is allowed to view all movies for Jio Mobile subscribers , Kindly resolve the issue, Regards

**Comment by Vikassm73** [comment]
as told previously, I need a debug log

**Comment by Varun23102002** [comment]
Bro we got it but debug log kaha pe milega kodi m

**Comment by Vikassm73** [comment]
You need to enable below setting. After that do logout and login. After that send me the kodi.log

Android path may be
/data/org.xbmc.kodi/cache/temp/kodi.log
/sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

Under Windows    =   %APPDATA%\Kodi\kodi.log

![image](https://user-images.githubusercontent.com/41675437/213670259-ee674636-2426-47f7-b3c8-7900d9185f64.png)

**Comment by bumehta17031947** [comment]
2023.01.20 14:21:42.509 T:1596 INFO<general>:Initializing python engine
2023.01.20 14.21:09.314 T:12500 INFO<general> Python interpreter stopped
2023.01.20 14.21:09.151 T:12500 INFO<general> C Python Invoker 65

Above is the log file after Jio Cinema failed to open movie after Jio number logged in

**Comment by Vikassm73** [comment]
I always need complete log file... 2-3 lines are not useful. you can send it on vikassm73@gmail.com.

Try modified addon

[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10465515/plugin.video.jiocinema.zip)

**Comment by ganesh-user** [comment]
unable to install Jio Cinema add-on. Getting message "failed to install dependencies"

**Comment by Vikassm73** [comment]
New jiocinema addon. Please try this for valid license and confirm.


[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10497861/plugin.video.jiocinema.zip)

**Comment by bumehta17031947** [comment]
It is working perfectly after logged in with jio number, kindly update your
repository file, salute to you 🙏🏻🙏🏻🙏🏻

**Comment by virubhai22** [comment]
unable to install Jio Cinema (failed to install dependencies) plz fix it @Vikassm73

**Comment by Vikassm73** [comment]
Please check the name of dependency. You can search for it and can able to install it manually. You will get those dependency if you install my hotstar addon

**Comment by Vikassm73** [comment]
Updated version of Jio Cinema

[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10545115/plugin.video.jiocinema.zip)

**Comment by bumehta17031947** [comment]
Ok, I will install it and give you feedback , actually if re login is
required or not can be checked tomorrow only
Regards

**Comment by virubhai22** [comment]
Unable to play live match like cricket ,football (SA20 and other FOOTBALL LEAGUE) LIVE in Jio Cinema addon i send log file on your gmail plz find out

**Comment by Vikassm73** [comment]
> Unable to play live match like cricket ,football (SA20 and other FOOTBALL LEAGUE) LIVE in Jio Cinema addon i send the log file on your gmail @Vikassm73 plz find out

It is difficult to test as I don't have any valid subscription and secondly for testing, we need to wait for the live event.

**Comment by virubhai22** [comment]
> > Unable to play live match like cricket ,football (SA20 and other FOOTBALL LEAGUE) LIVE in Jio Cinema addon i send the log file on your gmail @Vikassm73 plz find out
> 
> It is difficult to test as I don't have any valid subscription and secondly for testing, we need to wait for the live event.

live cricket event (SA20) now available on daily 5pmIST

**Comment by virubhai22** [comment]
live event issue is still not working on jio cinema add on @Vikassm73  plz fix it

**Comment by grace764** [comment]
> "failed to install dependencies"

@Vikassm73 "failed to install dependencies" getting this error even when using latest zip
