### ISSUE TITLE
Sonyliv error

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#154]
Sony liv content are not playing

**Comment by Fjfjrixi** [comment]
Sonyliv are not working please fix this problem

**Comment by LoCo8472** [comment]
If u have android tv try aostv application almost all working

**Comment by Fjfjrixi** [comment]
> If u have android tv try aostv application almost all working

Sonyliv content are not available

**Comment by Fjfjrixi** [comment]
Please reply

**Comment by ganesh-user** [comment]
> Please reply

H96 Android Box, Kodi Version- 19.3
To me Sonyliv is working as usual without any problem. Except the current problem of stucking / exiting during advertising breaks. 
When did error started for you?

**Comment by Vikassm73** [comment]
There is no issue in Sonyliv (Except in Live Channels). Do clear log and try again
