### ISSUE TITLE
Jiotv Addon Plugin video

### ISSUE THREAD

**Issue by bumehta17031947** [Vikassm73/AjaykRepo#157]
on 21st, jiotv application updated by reliance as a result jiotv stopped working on Kodi. Some one have posted the solution on botallen repository on issue no 364, this solution is posted on google drive and Amazon fire tv stick do not support google drive as a result fire tv stick user could not updated their jiotv addon and hence not working.Requesting to post its solution on this thread of your repository to enable the fire tv stick user to download and update it. Pl help, thanks in advance.Regards

**Comment by Vikassm73** [comment]
I am not using Jio hence can't test it but downloaded and upload for you

[plugin.video.jiotv.zip](https://github.com/Vikassm73/AjaykRepo/files/10487837/plugin.video.jiotv.zip)

**Comment by Vikassm73** [comment]
Also, found other zip in the same thread

[plugin.video.jiotv-1.0.3.zip](https://github.com/Vikassm73/AjaykRepo/files/10487854/plugin.video.jiotv-1.0.3.zip)

**Comment by bumehta17031947** [comment]
https://drive.google.com/drive/folders/1wGMkB5dzQuOm2IbycSjoUa-FAu71QNLE

Above is link to download the zip file which works can you pl download it and pest it, Regards

**Comment by Vikassm73** [comment]
I have uploaded the same

**Comment by bumehta17031947** [comment]
Thank you Vikasbhai, hope you will come back on JioCinema addon , Regards

**Comment by MKD1995** [comment]
> Also, found another zip in the same thread
> 
> [plugin.video.jiotv-1.0.3.zip](https://github.com/Vikassm73/AjaykRepo/files/10487854/plugin.video.jiotv-1.0.3.zip)

Sir can you maintain this add-on plz 🙂

**Comment by Vikassm73** [comment]
I am not a Jio user, so not using Jio app. I don't know scraping from Android app and only work on web application.

**Comment by bumehta17031947** [comment]
Web application is  jiocinema.com  , you can see on that or on iso
jiocinema application , Regards

**Comment by Vikassm73** [comment]
I was talking about JioTV app. 
In Jiocinema, I am not able to test it with valid subscription.

**Comment by mdriyas92** [comment]
> https://drive.google.com/drive/folders/1wGMkB5dzQuOm2IbycSjoUa-FAu71QNLE
> 
> Above is link to download the zip file which works can you pl download it and pest it, Regards

This one working like pro , But once after that today the app is updated in to Kodi nexus from that moment the  app is continuously crash when the jiotv play the streams. 
so i am going back to Kodi Metrix

**Comment by virubhai22** [comment]
jio cinema not working properly

**Comment by bumehta17031947** [comment]
Thank you Very mush Sir, Jio Cinema is working after signing in , Kindly update this plugin on your repository file and confirm, With warm regards

**Comment by Vikassm73** [comment]
Good. I will do some more testing and then upload it.

**Comment by bumehta17031947** [comment]
Ok

**Comment by bumehta17031947** [comment]
Now all sections of jiocinema is working very well and not limited to movie
sections, just for your information, Regards

**Comment by bumehta17031947** [comment]
Following is the link of JIOTV web application on google chrome to develop the Jiotv addon

https://chrome.google.com/webstore/detail/watch-jio-tv-on-pclaptop/mbniflppgoiiiaiifikgakocbloonpib

kindly do something as botallen is almost out and it helps the most user ,Regards

**Comment by Vikassm73** [comment]
I have already checked that. It is useless. You need to use any android emulator.

**Comment by snowdog05** [comment]
For Jio TV, I tried this today: https://github.com/avipatilpro/JioTV
Note: I used it on desktop only, channels are working fine.

**Comment by Mathod289** [comment]
Jio tv ads to update are continuously being played on loop , I am using Jio tv add on on kodi on firestick ..pls assist

**Comment by mdriyas92** [comment]
> Jio tv ads to update are continuously being played on loop , I am using Jio tv add on on kodi on firestick ..pls assist

Please check above comments of me to resolve this

**Comment by bumehta17031947** [comment]
pl send your e mail address , i will mail you

**Comment by bumehta17031947** [comment]
Vikasbhai, further feedback on jiocinema , when Kodi is shutdown , it is
automatically logged out and re login required, which needs to be resolved
, it should be like SonyLIV addon of yours, hope you will resolve it

**Comment by Mathod289** [comment]
> > Jio tv ads to update are continuously being played on loop , I am using Jio tv add on on kodi on firestick ..pls assist
> 
> Please check above comments of me to resolve this

Already used the zip u shared .. not all channels working ..

**Comment by Mathod289** [comment]
> pl send your e mail address , i will mail you
Way to dm on this forum.. will share my id
Is there ac

**Comment by jamalfeb1** [comment]
Pls send me the method

**Comment by jamalfeb1** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
***@***.*** Thanks  Sent from Mail for Windows From: Mathod289Sent: Thursday, January 26, 2023 4:27 PMTo: Vikassm73/AjaykRepoCc: SubscribedSubject: Re: [Vikassm73/AjaykRepo] Jiotv Addon Plugin video (Issue #157) pl send your e mail address , i will mail youWay to dm on this forum.. will share my idIs there ac—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ganesh-user** [comment]
@Vikassm73 This thread has mixed-up between Jio TV add-on and Jio cinema add-on. And hence causing confusion. Kindly update this thread to be only  Jio TV add-on thread.

**Comment by Liva1525** [comment]
Jiotv plugin not working

**Comment by 29television** [comment]
Jiotv plugin not working since morning in kodi.why this plugin problem is arising after working for somedays. Please find a permanent solution to this problem.

**Comment by varunganjoo** [comment]
JIO TV AGAIN NOT WORKING ON KODI AGAIN ,ANY SOLUTION

**Comment by bumehta17031947** [comment]
JioTV stopped working from this morning, experts can help the community to
resolve this issues as botallen repository has stopped total supports

**Comment by phormskaran** [comment]
Yes same here channels are not playing anymore kindly solution

**Comment by kmljt** [comment]
@bumehta17031947 kindly share the solution here if you find one.

**Comment by jamalfeb1** [comment]
Can't we create a plugin or have alternative solution for jio tv where we
can watch all channels.

Regards
Jameel shmed

**Comment by Rockyglax202024** [comment]
> Good. I will do some more testing and then upload it.

Please upload jio cinema updated version while opening the jio cinema all the videos showing update the app please provide updated version as soon as possible 🙏🙏
