### ISSUE TITLE
[Request] Vi (Vodafone) TV shows and movies addon

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#16]
Would love if you can also  make Vi (Vodafone) TV shows and movies addon where we can login using vodafone mobile number and OTP.

**Comment by Vikassm73** [comment]
OTP based applications are difficult to implement that is the reason I avoid application like VI and airtelxtreme.

**Comment by iamnewtogithubhelpme** [comment]
Thanks for the reply. I hope there was I'd password for these apps or at least web login.
