### ISSUE TITLE
Zee5 not work after Login

### ISSUE THREAD

**Issue by Nexus-Gits** [Vikassm73/AjaykRepo#160]
After login on Zee5 account, Zee 5 (2.1.20) not working on Kodi 20. Show error also when opening. Without login free channel works fine. Please let me know how to fix that issue. @Vikassm73 & @nikhilk0 .

**Comment by ganesh-user** [comment]
> After login on Zee5 account, Zee 5 (2.1.20) not working on Kodi 20. Show error also when opening. Without login free channel works fine. Please let me know how to fix that issue. @Vikassm73 & @nikhilk0 .

Can you play free channels after Login ?

**Comment by Karveanjali** [comment]
No programs working on Zee5

**Comment by Nexus-Gits** [comment]
> > After login on Zee5 account, Zee 5 (2.1.20) not working on Kodi 20. Show error also when opening. Without login free channel works fine. Please let me know how to fix that issue. @Vikassm73 & @nikhilk0 .
> 
> Can you play free channels after Login ?

No, nothing work after login.

**Comment by Vikassm73** [comment]
Don't find any issue. Are you facing issue of Device ID? Try to delete device id from settings and try again

**Comment by Nexus-Gits** [comment]
> 

I also do that but nothing work. Afeter login all time it shows error & nothing open in zee5.

**Comment by Vikassm73** [comment]
Send me a log with debug enabled
