### ISSUE TITLE
Which voot subscription plan to use in voot add-on?

### ISSUE THREAD

**Issue by snowdog05** [Vikassm73/AjaykRepo#162]
Hi,
I was using JioTv add-on to watch live TV. As the Add-on stopped working, I am confused in which voot plan to select for using your voot add-on. I want to watch Colors Marathi live, mostly on TV only. So, will voot mobile plan (Rs. 299) will work with your add-on or i have to purchase othe plan? (Rs.499 Gold or Rs.599 Platinum). Please help.

**Comment by virubhai22** [comment]
VI MOVIES AND TV is the best for Live TV and other Voot and Zee5 content, i think @Vikassm73 should make this add on

**Comment by snowdog05** [comment]
Anyone using voot mobile plan to watch live channels on TV with this add-on?
