### ISSUE TITLE
Jio tv channals are not playing

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#163]
Jio tv not working after login channals are not playing please add in your repository and update and fix this error

**Comment by Fjfjrixi** [comment]
Please reply me

**Comment by ganesh-user** [comment]
> Please reply me

read this below link given open thread
https://github.com/Vikassm73/AjaykRepo/issues/159

**Comment by shmbub2** [comment]
use this 
https://github.com/boredom1234/plugin.video.jiotv/releases/download/v2.0/plugin.video.jiotv-main_2.0.api.zip

**Comment by Fjfjrixi** [comment]
Installation failed in kodi not working please fix 😫😫
