### ISSUE TITLE
SonyLIV Error

### ISSUE THREAD

**Issue by wildgamharsh** [Vikassm73/AjaykRepo#164]
Sonyliv is not playing on Kodi as it shows Playback Failed
![Kodi 2_8_2023 9_52_20 PM (1)](https://user-images.githubusercontent.com/95742156/217590069-07c39276-440e-45b0-bcb8-23df5889d335.png)

**Comment by wildgamharsh** [comment]
please provide a solution for it

**Comment by Vikassm73** [comment]
Tested, working fine. Please "Clear log" and try again. If specific module is not working then let me know

**Comment by wildgamharsh** [comment]
I tried clearing log and then tried to log in but there is and error sending otp any solution please

**Comment by wildgamharsh** [comment]
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/10792039/kodi.log)
I have attached the log file for you to analyze

**Comment by wildgamharsh** [comment]
it worked thanks
