### ISSUE TITLE
Zee5 no sound

### ISSUE THREAD

**Issue by nabakumarchow** [Vikassm73/AjaykRepo#165]
No sound on zee5 addon

**Comment by snowdog05** [comment]
When i fast forward video in zee5, it hangs up. unable to play any other video until kodi is force stopped and restarted.

**Comment by nabakumarchow** [comment]
There is no sound in zee5 of every device which i am using with this kodi plugin

**Comment by Vikassm73** [comment]
In setting, set  "Play List" to Select. You will get option of choosing stream. Please try different stream and confirm

**Comment by nabakumarchow** [comment]
Not working bro

**Comment by nabakumarchow** [comment]
If i select steam 1 then no audio and if we select other stream then it's showing one or more items failed to play

**Comment by Vikassm73** [comment]
have you tested multiple streams? I have tested, it was working fine.

**Comment by nabakumarchow** [comment]
Using stream link 2 ?

**Comment by nabakumarchow** [comment]
> 

Bro hotstar and sonyliv of your repository is working fine but the problem is only with zee5

**Comment by Vikassm73** [comment]
> Using stream link 2 ?>

No, Link 1. Second does not work under windows because of VMP Issue. Don't find any issue. You check non premium one

**Comment by nabakumarchow** [comment]
Link 1 has no sound in my tv but on another tv which have 19.5 kodi working fine . But the tv of my bedroom and my pc having the problem . My tv does not work with 19.5 kodi

**Comment by Vikassm73** [comment]
I have tested in 19.4 installed on my windows PC

**Comment by nabakumarchow** [comment]
My pc has 19.5 it is working but my tv does not support 19.5

**Comment by snowdog05** [comment]
@Vikassm73 video hangs when fast forwarded on zee5 add-on. when video hangs, it actually makes kodi unresponsive as no other video plays untill kodi restart. I noticed this issue on Latest Hindi episodes free / Latest Marathi episodes free
tested on android TV, Kodi 19.5

**Comment by Vikassm73** [comment]
It could be issue of Less Memory. I have tried under windows, It works find. Sometimes, it gets closed but again you can able start from the same place.

**Comment by virubhai22** [comment]
@snowdog05 @nabakumarchow @Vikassm73 for no audio issue  solution is here plz downgrade  **Inputstream Adaptive** version

**Comment by snowdog05** [comment]
@virubhai22 i am not facing no sound issue, i am facing crash on fast forward issue.
@Vikassm73 Yes you are right, this might be memory issue. I tried on my phone and tab, fast forward works seamlessly, but on TV it crashes.

**Comment by Vikassm73** [comment]
On TV, instead of fast forward, you can use Kodi remote (Mobile App) or even TV remote for jump forward.

**Comment by shri1990** [comment]
> I have tested in 19.4 installed on my windows PC. Please check if Kodi 20 is possible.

Tried in Kodi 20, still audio issue is there in Zee5 with both premium and free content aswell..

**Comment by shri1990** [comment]
> @snowdog05 @nabakumarchow @Vikassm73 for no audio issue solution is here plz downgrade **Inputstream Adaptive** version

Downgrading the inputsteam might create other compatibility issues with other addons?

**Comment by virubhai22** [comment]
> > @snowdog05 @nabakumarchow @Vikassm73 for no audio issue solution is here plz downgrade **Inputstream Adaptive** version
> 
> Downgrading the inputsteam might create other compatibility issues with other addons?
![WhatsApp Image 2023-02-15 at 8 22 30 PM (1)](https://user-images.githubusercontent.com/115803193/219064417-2783b38e-e1e6-43bf-823d-34c22ef0cc3d.jpeg)
Dont worry if u change ur **InputStream adaptive** version to **2.3.2** no problem occurs, I m using it myself, I have also attached photo

**Comment by nabakumarchow** [comment]
> @snowdog05 @nabakumarchow @Vikassm73 for no audio issue solution is here plz downgrade **Inputstream Adaptive** version

How to do it bro

**Comment by snowdog05** [comment]
@Vikassm73 I updated my kodi version to 20 and the fast forward issue is solved. But there is no sound in zee5. so to summarize, the issue is No sound in zee5 addon in Kodi version 20.
@virubhai22 I tried to downgrade the InputStream Adaptive version, It shows me 2 versions 20.3.3 and 19.X.X. I tried to install 19.X.X but it failed to install.

**Comment by virubhai22** [comment]
> > @snowdog05 @nabakumarchow @Vikassm73 for no audio issue solution is here plz downgrade **Inputstream Adaptive** version
> 
> How to do it bro

Go to setting **-Add ons** - **My add ons** - **VideoPlayer InputStream** - **Inputstream Adaptive** - **Versions** - **20.3.2**

**Comment by snowdog05** [comment]
@virubhai22 Yes, audio works with Inputstream Adaptive version 20.3.2
It works by downgrading to this version on my phone, but there is no option for 20.3.2 on TV.
I tried to downgrade by installing manually,  but zip fails to install.
So, this is Inputstream Adaptive version 20.3.3 issue. I guess this issue is reported here https://github.com/xbmc/inputstream.adaptive/issues/1132
We need to wait for the next update.

**Comment by Vikassm73** [comment]
In Input Stream Adaptive Information, There might be previous version in Local Cache. Please check

**Comment by snowdog05** [comment]
> In Input Stream Adaptive Information, There might be previous version in Local Cache. Please check

Local Cache have 2 versions 20.3.3 and 19.X.X on my TV. I tried to install 19.X.X but it failed to install.

**Comment by Vikassm73** [comment]
19.x.x is for Kodi 19 not 20. Either you have to try it manually or wait for new version.

**Comment by virubhai22** [comment]
> @virubhai22 Yes, audio works with Inputstream Adaptive version 20.3.2 It works by downgrading to this version on my phone, but there is no option for 20.3.2 on TV. I tried to downgrade by installing manually, but zip fails to install. So, this is Inputstream Adaptive version 20.3.3 issue. I guess this issue is reported here [xbmc/inputstream.adaptive#1132](https://github.com/xbmc/inputstream.adaptive/issues/1132) We need to wait for the next update.

Download this kodi nexus u will get **InputStream Adaptive version 20.3.2** from here
https://mirrors.kodi.tv/nightlies/android/arm/master/kodi-20230127-84a596c2-master-27987-armeabi-v7a.apk

**Comment by snowdog05** [comment]
@virubhai22 @Vikassm73 InputStream Adaptive version 20.3.4 is released now. I updated plugin on kodi 20, Now zee5 has sound.

**Comment by virubhai22** [comment]
> @virubhai22 @Vikassm73 InputStream Adaptive version 20.3.4 is released now. I updated plugin on kodi 20, Now zee5 has sound.

yes i also got new update and working fine
