### ISSUE TITLE
Jio tv not working problem

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#166]
Jio tv channals are not playing please add in your repository and update and fix this 🥺🥺

**Comment by snowdog05** [comment]
Please try this https://github.com/Vikassm73/AjaykRepo/issues/159#issuecomment-1434136415

**Comment by Fjfjrixi** [comment]
> Please try this [#159 (comment)](https://github.com/Vikassm73/AjaykRepo/issues/159#issuecomment-1434136415)

its working fine thank you 😊😊
