### ISSUE TITLE
Error sending otp 

### ISSUE THREAD

**Issue by wildgamharsh** [Vikassm73/AjaykRepo#167]
i have error in kodi it shows that there is an error sending otp 
below is the log file please analyze it and provide the solution
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/10792065/kodi.log)

**Comment by Vikassm73** [comment]
Don't find any issue. Any way, Install below plugin manually and try again

[plugin.video.sonyliv.zip](https://github.com/Vikassm73/AjaykRepo/files/10802457/plugin.video.sonyliv.zip)

**Comment by wildgamharsh** [comment]
it worked thank you for the support
