### ISSUE TITLE
Voot crashes Kodi 

### ISSUE THREAD

**Issue by satyajitd111** [Vikassm73/AjaykRepo#168]
Watching something for 10-15mins in voot causes kodi to crash

**Comment by Vikassm73** [comment]
This might be problem of Kodi. Just reinstall it again. Here, I have tested and it is working fine.

**Comment by satyajitd111** [comment]
I did actually but same result, it seems to be the problem with Voot only.
Play Big Big Boss>>S04
Crashes Kodi after playing some minutes
OS: [LibreELEC-Generic-legacy.x86_64-10.95.1]

**Comment by snowdog05** [comment]
@satyajitd111 do you have voot premium subscription plan? If yes, please tell which plan you are using. I want to buy voot premium but confused if voot mobile plan works in kodi tv or not.
