### ISSUE TITLE
Zee5 error..

### ISSUE THREAD

**Issue by Daredevil1092** [Vikassm73/AjaykRepo#171]
![Screenshot_20230306-104241_Kodi](https://user-images.githubusercontent.com/112254137/223024566-1dad9f91-2b42-4094-a23c-5a7bd47e1c83.jpg)

This error occurs when I log in..

**Comment by Vikassm73** [comment]
Please send me debug log. I don't find any issue. Some times, just clearing cache gets this problem solved.

**Comment by Daredevil1092** [comment]
Here's the log file

[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/10931470/kodi.log)

**Comment by snowdog05** [comment]
This issue is very random and seems to be with zee5 servers. I am using this without login and sometimes it gives error. But after some time (5-10 min) it starts working.
