### ISSUE TITLE
Unable to play WPL in Jio cinema add on.

### ISSUE THREAD

**Issue by KriezParker** [Vikassm73/AjaykRepo#172]
Hi, I am unable to play WPL live match on Jio Cinema. When we click the match listed in multiple language it is not responding.
Also tried right click and play. Its still not working.
Could you please look into it.
I am using Kodi Nexus 20.

**Comment by Vikassm73** [comment]
[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10941423/plugin.video.jiocinema.zip)


Install this add-on manually. After few testing, I will upload this in main repository.

**Comment by KriezParker** [comment]
Unable to install zip file. It is throwing below error
![20230310_200833](https://user-images.githubusercontent.com/125632344/224344257-12895da7-a9fd-486a-86e4-c9e435d3067d.jpg)

**Comment by virubhai22** [comment]
> [plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/10941423/plugin.video.jiocinema.zip)
> 
> Install this add-on manually. After few testing, I will upload this in main repository.
> 
> Use "Old Method" from Settings for Live Events.

working fine but plz add stream quality option

**Comment by KriezParker** [comment]
@virubhai22 
How did you install this zip file.? I tried install from zip file but didn't work. Also may I know what is old method from settings??

**Comment by virubhai22** [comment]
> @virubhai22 How did you install this zip file.? I tried install from zip file but didn't work. Also may I know what is old method from settings??

first download Ajayk Repo repository and install the open **Ajayk Repo** repository and download and install **SMR Link Tester** only. then install Jiocinema zip file manually.

**Comment by KriezParker** [comment]
@Vikassm73 @virubhai22 Now I can able to install and play. Thanks for your support Bro.

**Comment by grace764** [comment]
@KriezParker @virubhai22 Where do we get this SMR Link Tester also getting error when trying to Jiocinema zip file manually
