### ISSUE TITLE
Jio tv not working please add into our repo and update

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#173]

**Comment by Fjfjrixi** [comment]
I was comment many time please reply and solve jio tv problem

**Comment by snowdog05** [comment]
Have you tried this? 
https://github.com/Vikassm73/AjaykRepo/issues/159#issuecomment-1455902122
This zip is working for me. EPG is not working.

**Comment by Fjfjrixi** [comment]
> 

its working thanks but ajay repository should also add jio tv in our repository like hotstar

**Comment by Vikassm73** [comment]
Jio Tv is not my baby. secondly may or may not able to maintain it that's why not added in my Repo.

**Comment by Fjfjrixi** [comment]
> Jio Tv is not my baby. secondly may or may not able to maintain it that's why not added in my Repo.
Please request from botallan to add jio tv in your repo like hotstar

**Comment by Amaresh1978** [comment]
> > 
> 
> its working thanks but ajay repository should also add jio tv in our repository like hotstar

Vikassm73 bro can you tell me that to watch hotstar in your Ajay repository do I need subscription?

**Comment by Vikassm73** [comment]
> > > 
> > 
> > 
> > its working thanks but ajay repository should also add jio tv in our repository like hotstar
> 
> Vikassm73 bro can you tell me that to watch hotstar in your Ajay repository do I need subscription?

Need a subscription for premium content only. Free contents are available without subscription.
