### ISSUE TITLE
Hotstar issue 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#174]
No sound problem in some series please fix

**Comment by nabakumarchow** [comment]
> No sound problem in some series please fix

Same after updating

**Comment by Vikassm73** [comment]
Let me know in which series you are facing problem

**Comment by Fjfjrixi** [comment]
Dheere dheere se

**Comment by nabakumarchow** [comment]
Which version of kodi you are using

**Comment by Vikassm73** [comment]
Kodi 19. Just noticed that Kodi 20 has an issue.

**Comment by nabakumarchow** [comment]
> Kodi 19. Just noticed that Kodi 20 has an issue.

Kodi 20.1 i am using .any method to resolve it?

**Comment by Vikassm73** [comment]
Let me check. Until then you can use Kodi 19.5.

**Comment by nabakumarchow** [comment]
Any update bro

> Let me check. Until then you can use Kodi 19.5.

**Comment by nabakumarchow** [comment]
> Let me check. Until then you can use Kodi 19.5.
Any update bro . I am waiting for your reply

**Comment by Vikassm73** [comment]
No..There may be problem in Kodi 20 Inputstream

**Comment by nabakumarchow** [comment]
Is there any solution?

**Comment by raulbha2** [comment]
Hey @Vikassm73 , did you happen to found out the issue, this seems to be troubling me too

**Comment by Vikassm73** [comment]
Noticed that new episodes are working fine.

**Comment by raulbha2** [comment]
@Vikassm73 thanks for the reply, it a bit or miss case it works sometimes and it doesn't sometimes, anyways with few retries everything works.
