### ISSUE TITLE
Zee5

### ISSUE THREAD

**Issue by fluss45** [Vikassm73/AjaykRepo#175]
Need help with zee5 run Linux sever 

can you please share how to run it on server without kodi 
Or convert this code to Php

thanks

**Comment by Vikassm73** [comment]
This will not work without Kodi. Under Linux, you have to install Kodi first then add-ons.

**Comment by fluss45** [comment]
Thanks for information.

Can you help me to convert this into Php ?

**Comment by Vikassm73** [comment]
This can't be done.
