### ISSUE TITLE
Zee5 error

### ISSUE THREAD

**Issue by smcoder0707** [Vikassm73/AjaykRepo#177]
Zee5 Not working.

Kodi log here - https://pastebin.com/raw/CZihjKzE

**Comment by Vikassm73** [comment]
In Zee5 Settings, Set "PlayBack Set" Seting to "Select" and then while playing, Select "Stream 2"

**Comment by smcoder0707** [comment]
> In Zee5 Settings, Set "PlayBack Set" Seting to "Select" and then while playing, Select "Stream 2"

Working fine now. But what is "Stream 1"...Is that a different quality?

Maybe you should add this instruction to the readme?

**Comment by Vikassm73** [comment]
"Stream 1" is "m3u8" link while "Stream 2" is "mpd" link. Some times, In case of premium movies, "Stream 1" use SAMPLE-AES encryption which is not supported in Kodi. In  that case, we need to use "Steam 2"
