### ISSUE TITLE
Jio tv add on request

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#178]
Please make a jio tv add on or pick from botallen repository and fix jio tv channals not working

**Comment by grace764** [comment]
@Fjfjrixi use this plugin from other developer working perfectly https://github.com/krreet/plugin.video.jiotv/releases

**Comment by grace764** [comment]
> Please make a jio tv add on or pick from botallen repository and fix jio tv channals not working

@Fjfjrixi use this plugin from other developer working addon https://github.com/krreet/plugin.video.jiotv/releases

**Comment by grace764** [comment]
If you need latest updates check this discord https://discord.gg/MgtR9EQxz5

**Comment by snowdog05** [comment]
> > Please make a jio tv add on or pick from botallen repository and fix jio tv channals not working
> 
> @Fjfjrixi use this plugin from other developer working addon https://github.com/krreet/plugin.video.jiotv/releases

This Add-on is very good.
Very less buffering and EPG also working.
Thank you for sharing.

**Comment by snowdog05** [comment]
Go to the Github link provided in comment and download latest released zip (click on Source code
(zip) to download file). Install this zip in kodi, login with your jio number, setup pvr and restart kodi.
