### ISSUE TITLE
Jio cinema not working

### ISSUE THREAD

**Issue by grace764** [Vikassm73/AjaykRepo#182]
Jio cinema not working from today

**Comment by Vikassm73** [comment]
Major api changes. need to start from scratch. It will take time.

**Comment by grace764** [comment]
@Vikassm73 Hope it will start soon because IPL will be broadcast on it though we can install official jiocinema app but having addon at one place in kodi is easy to access and less clutter

**Comment by Vikassm73** [comment]
New Version updated

**Comment by grace764** [comment]
Thanks it's working. Please add in repo because in repo 1.0.1 shows

**Comment by nabakumarchow** [comment]
I have jio cinema in kodi . But where to watch ipl

**Comment by Vikassm73** [comment]
It is available at "TATA IPL" - "Sport Carousel"

**Comment by Vikassm73** [comment]
What problem you are facing???

**Comment by nabakumarchow** [comment]
I have installed it from repository but no option for ipl

**Comment by Vikassm73** [comment]
After Execution are getting this menu

![image](https://user-images.githubusercontent.com/41675437/229460548-88486840-b8d6-4c03-8896-7f62f32763c9.png)

If yes then select "TATA IPL" - "Sport Carousel"

**Comment by nabakumarchow** [comment]
No bro

**Comment by nabakumarchow** [comment]
I am not getting this

**Comment by Vikassm73** [comment]
upload image again

**Comment by nabakumarchow** [comment]
![Uploading IMG_20230403_144807_918.jpg…]()

**Comment by nabakumarchow** [comment]
![Uploading IMG_20230403_144807_918.jpg…]()

**Comment by nabakumarchow** [comment]
It is showing home , sports etc

**Comment by nabakumarchow** [comment]
![IMG_20230403_144807_918.jpg](https://user-images.githubusercontent.com/121857047/229470268-37ec1472-8b90-443f-b6cd-7ae67070e645.jpg)

**Comment by nabakumarchow** [comment]
> ![IMG_20230403_144807_918.jpg](https://user-images.githubusercontent.com/121857047/229470268-37ec1472-8b90-443f-b6cd-7ae67070e645.jpg)
> 
>@Vikassm73

**Comment by Vikassm73** [comment]
You are using old version.. Use 1.0.2. If you are not able to get it in the repo, download manually from https://github.com/Vikassm73/AjaykRepo/tree/main/Zips/plugin.video.jiocinema and install it

**Comment by nabakumarchow** [comment]
@Vikassm73  send me the zip please
. I am unable to download it
