### ISSUE TITLE
Jio Cinema app update message 

### ISSUE THREAD

**Issue by pshewale-dev** [Vikassm73/AjaykRepo#183]
![PXL_20230326_201019459](https://user-images.githubusercontent.com/79329378/227783296-6aa3da9a-d5e0-42e9-a8de-43cd1af38920.jpg)
Getting app update message on jio cinema addon

**Comment by Vikassm73** [comment]
New Version updated

**Comment by pshewale-dev** [comment]
Thanks.but how to watch IPL?

**Comment by Vikassm73** [comment]
May be it will available at "TATA IPL" - "Sport Carousel"

**Comment by pshewale-dev** [comment]
Working after update
