### ISSUE TITLE
Jio cinema app update 

### ISSUE THREAD

**Issue by Rockyglax202024** [Vikassm73/AjaykRepo#187]
Jio cinema 1.01 using when opened the it's asking update all channels playing but the video all show update the app please update soon want to watch IPL please update

**Comment by grace764** [comment]
#182 check this thread

**Comment by Rockyglax202024** [comment]
> #182 check this thread

Which thread?

**Comment by Vikassm73** [comment]
New Version updated

**Comment by MKD1995** [comment]
Is it working properly for u guys for me there was no audio in Hindi or English and also Kodi was crashing in under 5-7 sec when I played live match.

**Comment by ashish-katyal** [comment]
It is working for me, thanks 🙏❤

**Comment by grace764** [comment]
Yes it's working properly and even live ipl audio issue is resolved

**Comment by rajdeepdodiya** [comment]
I am getting a error when logging in using my mobile phone number. How did you guys login?

**Comment by Vikassm73** [comment]
Send me a debug log. Let me know what is an issue.

**Comment by rajdeepdodiya** [comment]
> Send me a debug log. Let me know what is an issue.

pfa
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/11257892/kodi.log)

**Comment by Vikassm73** [comment]
does jiocinema web works in canada??

**Comment by rajdeepdodiya** [comment]
> does jiocinema web works in canada??

No.

**Comment by Vikassm73** [comment]
Then it will not work at your region
