### ISSUE TITLE
sonyliv 4k support

### ISSUE THREAD

**Issue by borxR** [Vikassm73/AjaykRepo#189]
is it possible to add 4k res support for sonyliv?

**Comment by Vikassm73** [comment]
I have not added any restriction. If link has 4k stream, you have a 4k display and if you have not added any restriction in Inputstream, it should show.

**Comment by borxR** [comment]
> I have not added any restriction. If link has 4k stream, you have a 4k display and if you have not added any restriction in Inputstream, it should work. Set inputstream in manual mode and check yourself.

But I don't think it'll support 4k since you're using the sony web APIs in your plugin.
