### ISSUE TITLE
Voot asking premium subscription even though it is active

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#190]
I have been using voot addon for many months and never faced this issue. I have id password of my subscription put in the settings and premium videos always worked but suddenly since today, this has stopped and asks me to get premium subscription. Has something changed?

Also, once we enter id password for voot, can we get a confirmation if the login was successful or not?

**Comment by iamnewtogithubhelpme** [comment]
I usually watch Big boss marathi right now so just mentioning that so you can debug.

**Comment by Vikassm73** [comment]
just check whether you are able login on voot web? i.e. voot.com

**Comment by iamnewtogithubhelpme** [comment]
I tried in app on fire tv and also my phone and it is fine. I tried the addon in kodi on my fire stick and also android tablet and in both cases it told premium subscription required.

**Comment by iamnewtogithubhelpme** [comment]
I tried in app on fire tv and also my phone and it is fine. I tried the addon in kodi on my fire stick and also android tablet and in both cases it told premium subscription required.

**Comment by Vikassm73** [comment]
Enable debug logging. Press clear log and try to play any content. After that send me log file on vikassm73@gmail.com.

**Comment by iamnewtogithubhelpme** [comment]
Please check this link for log. Check from 11:55 time.

https://paste.kodi.tv/uceyeyudix

**Comment by Vikassm73** [comment]
this is normal log. Follow above instruction and send me log. also, you can try below add-on


[plugin.video.voot.zip](https://github.com/Vikassm73/AjaykRepo/files/11167159/plugin.video.voot.zip)

**Comment by iamnewtogithubhelpme** [comment]
I am not sure what you did but the zip you gave worked. I Uninstalled previous addon and installed the zip you gave and it worked fine and premium content is accessible now.

**Comment by Vikassm73** [comment]
New release updated in the repo.

**Comment by Mahaddip** [comment]
> I have been using voot addon for many months and never faced this issue. I have id password of my subscription put in the settings and premium videos always worked but suddenly since today, this has stopped and asks me to get premium subscription. Has something changed?
> 
> Also, once we enter id password for voot, can we get a confirmation if the login was successful or not?

Which plan do you use ? Phone or Gold or Platinum? please confirm so that i can purchase accordingly for kodi.

**Comment by Vikassm73** [comment]
try after some times or use another user. This add-on works for free accounts also.
