### ISSUE TITLE
Add New feature for voot 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#195]
Add go page feature in voot and other ott apps like sonyliv. I reach easily on starting episodes like click on go page search page no. And watch old episodes easily

**Comment by Vikassm73** [comment]
[plugin.video.voot.zip](https://github.com/Vikassm73/AjaykRepo/files/11258031/plugin.video.voot.zip)


Install above add-on manually and check the same

**Comment by Fjfjrixi** [comment]
> [plugin.video.voot.zip](https://github.com/Vikassm73/AjaykRepo/files/11258031/plugin.video.voot.zip)
> 
> Install above add-on manually and check the same

Which add on i can install for use go page feature

**Comment by Fjfjrixi** [comment]
Please reply

**Comment by Vikassm73** [comment]
See attached zip, install zip manually to update Voot addon

**Comment by Fjfjrixi** [comment]
> See attached zip, install zip manually to update Voot addon

Give me zip file or link
