### ISSUE TITLE
Sony liv tv frequent dropped

### ISSUE THREAD

**Issue by grace764** [Vikassm73/AjaykRepo#198]
Sony live channel goes off after sometime and again when click on it then start.
So it's like after every 10-15 minutes live channel goes off

**Comment by niranjantechofficial** [comment]
How u using this zip?

**Comment by grace764** [comment]
> How u using this zip?

Dowload zip file and upload in kodi
check some youtube guide

**Comment by Vikassm73** [comment]
Correction done for Live channels in new version

**Comment by grace764** [comment]
> Correction done for Live channels in new version

Thanks for the update
