### ISSUE TITLE
Disney + hotstar app

### ISSUE THREAD

**Issue by prtkvashishth** [Vikassm73/AjaykRepo#20]
I believe that it's gonna be biggest requirement from 1st September considering the changes in the hotstar plans. I request you to kindly add disney + hotstar as well in our bucket. Refer screenshots. 
![Screenshot_20210808-202604_Chrome](https://user-images.githubusercontent.com/82662354/128636454-70682c12-13fb-427b-8445-17617a5348e0.jpg)
![Screenshot_20210808-202556_Chrome](https://user-images.githubusercontent.com/82662354/128636457-1c305c60-3cfe-4034-9f89-e2e10256d09a.jpg)

**Comment by Vikassm73** [comment]
Disney Hotstar is already present

https://github.com/botallen/repository.botallen
