### ISSUE TITLE
Jiocinema playback failed

### ISSUE THREAD

**Issue by Dhanush10129** [Vikassm73/AjaykRepo#201]
When i play any content in jio cinema it show playback failed ,one or more item failed to play ,pls fix it

**Comment by Vikassm73** [comment]
Just re-login and test again

**Comment by snowdog05** [comment]
I am facing similar issue, tried re-login still it gives error (playback failed ,one or more item failed to play).

**Comment by Vikassm73** [comment]
are you facing this even in free channels?

**Comment by snowdog05** [comment]
yes

**Comment by Vikassm73** [comment]
[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/11649095/plugin.video.jiocinema.zip)


Install this and check again

**Comment by Dhanush10129** [comment]
> [plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/11649095/plugin.video.jiocinema.zip)
> 
> Install this and check again

Thanks its working

**Comment by Dhanush10129** [comment]
Is there any way to screen record that it's showing black screen on recorded video can u help me with that

**Comment by Vikassm73** [comment]
> Is there any way to screen record that it's showing black screen on recorded video can u help me with that

What exactly you want? Kodi is just a player. If recorded video is not supported by it, it won't play.

**Comment by techgamers2** [comment]
bro playback issue tried latest version and linked version here both dont work

**Comment by techgamers2** [comment]
> bro playback issue tried latest version and linked version here both dont work



> [plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/11649095/plugin.video.jiocinema.zip)
> 
> Install this and check again
bro playback issue tried latest version and linked version here both dont work

**Comment by Vikassm73** [comment]
If you are using valid logins, Login again otherwise Press logout and try to play again
