### ISSUE TITLE
Zee5 Only playing movie trailers

### ISSUE THREAD

**Issue by ibshar** [Vikassm73/AjaykRepo#202]
Zee5 addon is only playing the movie trailers instead of the actual full movie. I tried playing movies from Movies -> Zee5 Exclusive and Movies -> Bollywood Favorites, both places all the movies listed just play the trailer but no option to play the actual movie.

**Comment by Vikassm73** [comment]
Are you premium subscriber?  If a movie is exclusively available to premium users, only the trailer will play.

**Comment by ibshar** [comment]
Yes I have premium subscription and I have logged in using OTP. I am able to view these movies on PC using the same login but on kodi it just plays the trailers.

**Comment by Vikassm73** [comment]
Enable debug. Do re-login using OTP and send me kodi log on vikassm73@gmail.com

**Comment by Vikassm73** [comment]
Just I have played, it is working. In settings, Set Playback List to "Select" and try to play using stream 1 as well as stream 2 options.

**Comment by ibshar** [comment]
Thanks, I'll try that today and let you know.

**Comment by ibshar** [comment]
I tried changing it to select but still got only trailers and checking the video streams it had only 1 stream available. But then it again asked for OTP to login which I could not do as that phone is not available so I am closing the issue.
