### ISSUE TITLE
Zee5 add-on not working on tablet

### ISSUE THREAD

**Issue by snowdog05** [Vikassm73/AjaykRepo#203]
Hi, I am using Tablet, added this zee5 addon on kodi, but it is not working.
It shows "Zee5 Error. Check the log for more information.".
I tried everything like clearing cache, clearing data, re-installing add-on, re-installing kodi, using old zee5 zip, using latest zee5 zip etc. still no success. But this add-on works fine on my phone and TV.
Please find the attached kodi log. 
Thanks.
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/11561661/kodi.log)

**Comment by Vikassm73** [comment]
[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/11561939/plugin.video.zee5.zip)


Try above zip

**Comment by snowdog05** [comment]
> 

This zip have similar result ("Zee5 Error. Check the log for more information.")

**Comment by Vikassm73** [comment]
will you please re-send the log file

**Comment by Vikassm73** [comment]
Sorry, I believe the issue is with the background and not a Zed 5 add-on. I am unable to reproduce the same bugs over here, so I am unable to fix it.

**Comment by snowdog05** [comment]
I compared kodi logs from my mobile and tablet, it seems to be the issue is with tablet version of kodi as some dependency module fails to load / connect, due to which zee5 also fails to connect.

**Comment by snowdog05** [comment]
old version (Matrix) gives same error. Kodi logs are also similar.

**Comment by rushic24** [comment]
+1 zee5 not working from past few weeks

**Comment by rushic24** [comment]
log https://pastebin.com/jC2jR2Y0

**Comment by snowdog05** [comment]
this logs looks similar with my logs. Also, it fails to work with VPN also.

**Comment by technofreak24** [comment]
**ZEE5 addon Tested OK on 5 June 2023, 2:30 PM**
Live TV, Search and TV Shows are working perfectly fine with no errors 
KODI Nexus v20.1 on FireTV Stick 3rd Gen
Video with date and time on Discord link https://discord.com/channels/1069583196326469634/1069583197186293774/1115212704102219816

**Comment by snowdog05** [comment]
Yes, Zee5 addon working fine on android tv and phone perfectly for me, but not on tab. tried everything still no success.

**Comment by Vikassm73** [comment]
Try this new version in tablet

**Comment by snowdog05** [comment]
> Try this new version in tablet

Yes working fine on tablet now.  Thanks!
