### ISSUE TITLE
Not able to download the given zip file 

### ISSUE THREAD

**Issue by ajay01994** [Vikassm73/AjaykRepo#204]
Hi , i am unable to download your given zip file -[repository.ajayk-1.1.zip](https://github.com/Vikassm73/AjaykRepo/raw/main/Zips/repository.ajayk-1.1.zip). i tried with multiple devices but it doesnt get downloaded , Additionally the repo doesn't connect with kodi

**Comment by snowdog05** [comment]
Use different browser like chrome / Firefox to download zip. The zip URL is working fine.
Try to download it in your desktop / laptop and then transfer it into your device.

**Comment by grace764** [comment]
> Hi , i am unable to download your given zip file -[repository.ajayk-1.1.zip](https://github.com/Vikassm73/AjaykRepo/raw/main/Zips/repository.ajayk-1.1.zip). i tried with multiple devices but it doesnt get downloaded , Additionally the repo doesn't connect with kodi

No issue in downloading check if something is blocking or try to open link in incognito
