### ISSUE TITLE
JIOTV not working 

### ISSUE THREAD

**Issue by Amaresh1978** [Vikassm73/AjaykRepo#205]
JIOTV plugin version 2.0.25 not working on Kodi Nexus from 29/05/23, showing "Runtime Error". Channels are loading, epg working but, no playback.

**Comment by technofreak24** [comment]
Do Not post JioTV issues here !
Post on developer  [krreet's github page](https://github.com/krreet/plugin.video.jiotv/issues) or on [Discord](https://discord.gg/RmqZHBFT) 

Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great.
**You have to Logout and Login Again !!**
The login credential tokens expire on the 21st day from the previous login at the same time as observed by group members. There may be no need to re-login but only refresh the expired tokens with a click or auto-refresh triggered by a function in the python code.

**Comment by technofreak24** [comment]
Do Not post JioTV issues here !
Post on developer  [krreet's github page](https://github.com/krreet/plugin.video.jiotv/issues) or on [Discord](https://discord.gg/RmqZHBFT) 

Checked both plugin versions [**krreet v2.0.25**](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) and [**tobalan v2.3.3**](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.3) are working great.
**You have to Logout and Login Again !!**
The login credential tokens expire on the 21st day from the previous login at the same time as observed by group members.

**Comment by Amaresh1978** [comment]
Thanks for guidance
