### ISSUE TITLE
Jiocinema login doesn't stay persistent

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#207]
It seems Jio cinema login doesn't stay persistent. Say I login and then view some premium content and then shut off kodi and then say after 2 hours and try to again access say some other or same premium content and it says "Premium Subscription Required".

Can you please check?

**Comment by Vikassm73** [comment]
This is known issue. Jio cinema login does not sustain for longer time and need to login again. Lets hope that I will find  out solution.
