### ISSUE TITLE
Jio cinema audio issue 

### ISSUE THREAD

**Issue by grace764** [Vikassm73/AjaykRepo#209]
After recent Jio cinema update audio is not working

**Comment by technofreak24** [comment]
**JioCinema v 1.0.3** addon is working fine with audio on Amazon FireTV Stick 3rd Gen with **Amazon FireTV OS v 7.6.3.3 + KODI Nexus v 20.1 +  addon v 1.0.3**
Tested OK at 1:15 PM on 17 June 2023
![Uploading IMG_20230617_135846.jpg…]()

**Comment by technofreak24** [comment]
**JioCinema v 1.0.3** addon is working fine with audio on Amazon FireTV Stick 3rd Gen with **Amazon FireTV OS v 7.6.3.3 + KODI Nexus v 20.1 + JioCinema addon v 1.0.3**
Tested OK at 1:15 PM on 17 June 2023
![IMG_20230617_135846](https://github.com/Vikassm73/AjaykRepo/assets/121749085/30642f6b-98e8-428c-b705-28866d46268d)

**Comment by grace764** [comment]
> **JioCinema v 1.0.3** addon is working fine with audio on Amazon FireTV Stick 3rd Gen with **Amazon FireTV OS v 7.6.3.3 + KODI Nexus v 20.1 + JioCinema addon v 1.0.3** Tested OK at 1:15 PM on 17 June 2023 ![IMG_20230617_135846](https://user-images.githubusercontent.com/121749085/246596578-30642f6b-98e8-428c-b705-28866d46268d.jpg)

Not all but some of recorded show having audio issue In android TV which was working properly before update

**Comment by Vikassm73** [comment]
Let me know the name of exact show

**Comment by grace764** [comment]
> Let me know the name of exact show

Hum Saaf Saaf Hai

**Comment by Vikassm73** [comment]
Yes, there is an issue with HD Quality but if you choose video quality 640x368, you will get Sound. I will add option of choosing video quality in the next version of Jio Cinema.

**Comment by grace764** [comment]
> Yes, there is an issue with HD Quality but if you choose video quality 640x368, you will get Sound. I will add option of choosing video quality in the next version of Jio Cinema.

Yes it's working now after changing video quality
