### ISSUE TITLE
Jio Cinema Quality Issue

### ISSUE THREAD

**Issue by Mahaddip** [Vikassm73/AjaykRepo#210]
Please add quality option just like Hotstar and Voot, sometimes quality goes to very poor. either you can guide for setting too. Thanks in advance

**Comment by snowdog05** [comment]
Even on Jio Cinema official app, the quality is not good. If you are watching in full HD, it feels like you are watching it in 480p or 720p.

**Comment by Vikassm73** [comment]
Set Inputstream Adaptive "Stream Selection Type" to "Ask Quality". After that you will able to select required quality.

**Comment by technofreak24** [comment]
> Please add quality option just like Hotstar and Voot, sometimes quality goes to very poor. either you can guide for setting too. Thanks in advance

I added **Quality** option in JioCinema addon and it works good by showing **InputStream Adaptive "Ask-quality"**.
Also **News** shortcut on Home Screen of JioCinema, to open TV18 News channels quickly.
![jiocin1_093505](https://github.com/Vikassm73/AjaykRepo/assets/121749085/01391ccd-4ed7-44d0-988e-5f6c62f56101)
![jiocin2_093502](https://github.com/Vikassm73/AjaykRepo/assets/121749085/0da645a0-3715-44f3-9181-706f5e5e1061)
![jiocin3_093444](https://github.com/Vikassm73/AjaykRepo/assets/121749085/159f3f8f-9de2-4663-90ac-35e7d28a1293)

**Comment by Vikassm73** [comment]
Quality selection added in Settings.
