### ISSUE TITLE
Zee 5 still not working after recent update

### ISSUE THREAD

**Issue by supernakl** [Vikassm73/AjaykRepo#213]
Hi, want to update, that zee5 still plays only trial of 1 to 2 min and not full movie.
This is common on firestick and Android tv 
Please have it corrected. Thanks.

**Comment by Vikassm73** [comment]
If you don't have valid logins, it play only Trailer not movie.

**Comment by supernakl** [comment]
Sir, could you please tell, what is a valid  login, is it paid you are referring to.
Sorry to bother you.

**Comment by Vikassm73** [comment]
yes, if you bought paid subscription then those movie will work.

**Comment by supernakl** [comment]
Then maybe it is true for SONYLIV, HOTSTAR also.
We should have only paid subscription for watching.
Then why do we need KODI.
We can install individual apps to watch.
I am asking this as I am not aware of the technical details.
But for jiotv it is worth.

**Comment by Vikassm73** [comment]
Navigation is faster. Also, there are other advantages. Once you start using it, you will love it.

**Comment by grace764** [comment]
> Navigation is faster. Also, there are other advantages. Once you start using it, you will love it.

Yes it's less clutter and better to organize addons at one place in kodi and also installing individual app from play store will take more space than addon

**Comment by supernakl** [comment]
Ok, guys, thanks, I am clear now.
 I am using the app on Android tv and fore stick.
Any issue I will write back.
Should I close this issue.
