### ISSUE TITLE
Hotstar not working error issue 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#215]
Hotstar add on not working in kodi when i try to open Hotstar ad on but not opening then i try to login in Hotstar but this add on was not opening please fix this problem

**Comment by Vikassm73** [comment]
Do you know little bit programming?

From below path open addons\script.module.codequick\lib\urlquick.py and just comment go to line 63 and just comment it by adding # like below

# from requests.adapters import HTTPResponse

**Comment by Fjfjrixi** [comment]
Please update this add on as soon as possible otherwise you request from little bit programming for me

**Comment by Vikassm73** [comment]
Latest version of codequick is update just few hour before. This problem will get solved now.

**Comment by Mahaddip** [comment]
> Do you know little bit programming?
> 
> From below path open addons\script.module.codequick\lib\urlquick.py and just comment go to line 63 and just comment it by adding # like below
> 
> "# from requests.adapters import HTTPResponse"
> 
> Otherwise wait for next version of codequick which will be auto updated.

Its work. Thanks

**Comment by Fjfjrixi** [comment]
> Latest version of codequick is update just few hour before. This problem will get solved now. If not, download from here and install
> 
> https://github.com/willforde/script.module.codequick/releases/tag/v1.0.3

Problem solved thank x 😊😊
