### ISSUE TITLE
Jio tv addon (Tobalan Repo) is not working 

### ISSUE THREAD

**Issue by ksadda77** [Vikassm73/AjaykRepo#216]
Hi,
Jio tv addon (Tobalan Repo) is not working after Kodi version changed to 20.2. Do anyone have working addon links? Sorry Vikas for posting in this.
Regards,
Kiran

**Comment by technofreak24** [comment]
Solution to your issue is on the page https://github.com/krreet/plugin.video.jiotv/issues/83

Addon v2.3.7 can be found on [Tobalan's GitHub](https://github.com/tobalan/plugin.video.jiotv/releases/tag/2.3.7)
or
[krreet's GitHub](https://github.com/krreet/plugin.video.jiotv/releases/tag/2.3.7)

**Comment by lavish440** [comment]
Addon is working fine for me.
