### ISSUE TITLE
Jio cinema error issue

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#220]
Bigg boss ott 2 latest episodes not playing in jio cinema please check this error and fix this issue

**Comment by iamnewtogithubhelpme** [comment]
Not only BB OTT, nothing works. Someone on discord mentioned Jio changed CDM (or was it supposed to be CDN, not sure). I have opened this issue here with pics of the error too.

Would appreciate a fix soon.

**Comment by Fjfjrixi** [comment]
> Not only BB OTT, nothing works. Someone on discord mentioned Jio changed CDM (or was it supposed to be CDN, not sure). I have opened this issue here with pics of the error too.
> 
> Would appreciate a fix soon.

Give me solution

**Comment by iamnewtogithubhelpme** [comment]
> > Not only BB OTT, nothing works. Someone on discord mentioned Jio changed CDM (or was it supposed to be CDN, not sure). I have opened this issue here with pics of the error too.
> 
> > 
> 
> > Would appreciate a fix soon.
> 
> 
> 
> Give me solution 

I am not developer. Please give the developer sometime to fix it.

**Comment by bits-shreyash** [comment]
Jio has made a security update, which would break the parser's , the same has been the case with voot as well !

**Comment by Vikassm73** [comment]
New Version uploaded

**Comment by Vikassm73** [comment]
[plugin.video.jiocinema.zip](https://github.com/Vikassm73/AjaykRepo/files/12226656/plugin.video.jiocinema.zip)

Manually install this

**Comment by rahul-blazzze** [comment]
Jio cinema show episodes are playing in fast forward mode. Any way to get them play normally

**Comment by Vikassm73** [comment]
Let me what you are playing. I don't face such problem. In settings, set play quality to Ask Quality option. After that try to play the content. Select low resolution and check.

**Comment by rahul-blazzze** [comment]
I tried the plugin in my other setup. It's working fine. I think the issue is with some settings at my end. Thanks
