### ISSUE TITLE
Zee 5 ajak addons error problem

### ISSUE THREAD

**Issue by Bhai2210** [Vikassm73/AjaykRepo#227]
Please fix it zee 5 addon.

**Comment by Vikassm73** [comment]
From Settings, Delete Device ID manually entry and again try to play the content.

**Comment by MISAGAR** [comment]
Tired with deleting the device ID but no luck...still "Zee 5 error". Also, the Device ID repopulates after this error.

**Comment by Bhai2210** [comment]
Thank u .its working fine
