### ISSUE TITLE
Kodi Version

### ISSUE THREAD

**Issue by SSoft7** [Vikassm73/AjaykRepo#229]
Hello,

Which Kodi version is best for this repository?
I'm getting weird errors.

**Comment by MISAGAR** [comment]
19.5 Matrix

**Comment by Vikassm73** [comment]
Now, Nexus v20.2 is stable. You can move to it. But if your android is old and not supportive then better stick to Matrix 19.5

**Comment by Bhai2210** [comment]
Showing error when installing any addons like zee 5..showing ..the dependcy of the siz module  version 0.0 could not be satisfied

**Comment by Bhai2210** [comment]
In all version of kodi Nexus v20.2 , Matrix 19.5 error

**Comment by Vikassm73** [comment]
May be six module, Right? download and install it from https://github.com/benjaminp/six/tags

**Comment by SSoft7** [comment]
> Now, Nexus v20.2 is stable. You can move to it. But if your android is old and not supportive then better stick to Matrix 19.5

I'm not running kodi on android. I'm running kodi on PC. So this plugin will work on 20.2 for PC?

**Comment by Vikassm73** [comment]
This plugin will work on all version. If you do not have it, download and install it manually.
