### ISSUE TITLE
hotstar not working with Kodi:21 nightly build and inputstream.adaptive:21.1.3

### ISSUE THREAD

**Issue by swinder0161** [Vikassm73/AjaykRepo#233]
### Describe the bug
installed add-on: https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/plugin.video.hotstar/plugin.video.hotstar-1.2.2.zip
Try to play Cricket Asia cup stream: Sports -> Asia Cup -> India vs Pakistan match
There is error from input.adaptive
Not Working: kodi: 21.0-ALPHA2 & input.adaptive : 21.1.3
Working: Same plugin working well on Kodi:Nexus in Windows and Android Phone: input.adaptive : 20.3.12

## Expected Behavior
Playback should work

## Actual Behavior
Playback shows error

### To Reproduce
installed add-on: https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/plugin.video.hotstar/plugin.video.hotstar-1.2.2.zip
Try to play Cricket Asia cup stream: Sports -> Asia Cup -> India vs Pakistan match

1. 
2.
3.

### Debuglog
2023-09-02 15:00:38.206 T:4200505   error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 403: https://live12p.hotstar.com/hls/live/2024726/inallow-asiacup-2023/hin/1540024251/15mindvrm01041c55e31355409c98d85f4627ad910402september2023/master_apmf.m3u8?a=ns&hdnea=st=1693646937~exp=1693647537~data=ip%3dd58JPvHp1pKClTi1VRsdxe-userid%3dMYfwPgDplhWnuXHFbpTfcrUcln5VqHu92cZfUYxoTKZY-did%3dfEPhZ5UygwveUJ2GzTvp8QabIBIXpw6ER1LNBNBl3er3GHCGAbn4VUj-cc%3din-~hmac=03095a00fa09f4a2c2670be0d239b991701ec0a04ca030d743d16e841578fed0&ttl=86400&type=free&acl=/hls/live/2024726/inallow-asiacup-2023/hin/1540024251/15mindvrm01041c55e31355409c98d85f4627ad910402september2023/master_apmf

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/inputstream.adaptive/files/12503712/kodi.log)

### MPD/M3U8s/ISM

Manifest not available in the userdata folder

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
<img width="1680" alt="image" src="https://github.com/xbmc/inputstream.adaptive/assets/397543/98fce378-152c-4473-adf2-e7f32e2e9a77">

### Your Environment
Used Operating system: MAC OS 13.5

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0-Alpha2 nightly build ARM64 version
 - inputstream.adaptive version: 21.1.3

*note: Once the issue is made we require you to update it with new information should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by swinder0161** [comment]
I raised this issue to inputstream.adaptive https://github.com/xbmc/inputstream.adaptive/issues/1370

They asked to contact developer:

this is more likely an addon "hotstar" bug that has not updated the inputstream configuration for kodi 21,
please check deprecation note and new configurations:
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivestream_headers
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemanifest_headers-
these are also printed as warning on Kodi 20 log

if you are not the developer of "hotstar" you have to report this problem to "hotstar" addon repository
flagged as external resolution until we get a feedback addon author

**Comment by swinder0161** [comment]
To test on android use apk from link: https://ftp.halifax.rwth-aachen.de/xbmc/nightlies/android/arm64-v8a/master/kodi-20230902-d14ae357-master-arm64-v8a.apk

Same problem on macos and android with latest kodi v21

**Comment by Vikassm73** [comment]
I'm using mitmproxy to only observe traffic coming through the browser. I'm not sure if Kodi will work with it.
