### ISSUE TITLE
Edit repository 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#234]
Add dangal play add on for dangal tv shows and remove voot add on because all the voot content are shift on jio cinema and voot also suggest to access our content in jio cinema

**Comment by technofreak24** [comment]
> @Fjfjrixi Add dangal play add on for dangal tv shows 

@Fjfjrixi  Put these Live TV m3u8 links in KODI IPTV Simple Client Addon's M3U playlist file !
**Dangal / दंगल**
http://livectv.phando.com/8052/playlist.m3u8

**Dangal 2 / दंगल २**
http://livectv.phando.com/8051/playlist.m3u8

**Comment by Vikassm73** [comment]
Added in m3u playlist. No plan to work on Dangal Addon.
