### ISSUE TITLE
Discord link please

### ISSUE THREAD

**Issue by 4sure-subham** [Vikassm73/AjaykRepo#236]
Hey i am a new user to jio tv plugin on kodi app.
Please share the link to discord again

**Comment by technofreak24** [comment]
> @4sure-subham  Please share the link to discord again

Please find the invite link below (valid for 5 days) 
[**KODI Addons Discord Server**](https://discord.gg/v7kveRGu) 

Discussion for addons JioTV, JioCinema, ZEE5, Sony LIV, Disney+ Hotstar, Voot, YouTube and other m3u8 streaming links.

![addons_020407](https://github.com/Vikassm73/AjaykRepo/assets/121749085/6aeb3329-bd1d-45c0-8b73-cf5efcd882ee)
