### ISSUE TITLE
Provide go page feature in all add on

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#237]
Provide go page feature in all add ons for find any series episodes no. Easily like Sony LIV

**Comment by Vikassm73** [comment]
I have added this where there is possible. I will check it again and add it if possible.

**Comment by Fjfjrixi** [comment]
There are many problems to find episodes our remote betteries are dead to find 1000 2000 no. Of tv series episodes please try

**Comment by Vikassm73** [comment]
In which addon?

**Comment by Fjfjrixi** [comment]
> In which addon? Hotstar it is not possible.

Okk try in jio cinema

**Comment by Vikassm73** [comment]
added in new version

**Comment by Fjfjrixi** [comment]
> added in new version

Okk thanx 😊 one last request remove voot add on because all the content of voot are shifted in jio cinema and officially voot app was shut down

**Comment by Vikassm73** [comment]
I will remove it in next update.

**Comment by Fjfjrixi** [comment]
Okk 😊

**Comment by Fjfjrixi** [comment]
Some issue of go page feature in jio cinema after complete any series episodes page are not showing numerical key are showing again and again I have to fill page no. Again then page open again please fix

**Comment by Vikassm73** [comment]
I will check for this. For time being, if you want to jump at page 6, Jump to page 5. Press next page and play the content.

**Comment by Fjfjrixi** [comment]
> I will check for this. For time being, if you want to jump at page 6, Jump to page 5. Press next page and play the content.

In jio cinema Page are not showing after end of content only number keys are showing but in sonyliv after end the content page are showing please fix this in jio cinema

**Comment by Fjfjrixi** [comment]
Reply please

**Comment by Vikassm73** [comment]
New version updated

**Comment by Fjfjrixi** [comment]
> New version updated

Good work thanks 😊😊 and add in mx player hotstar and zee 5 this is very helpful feature i find any series any episodes very easily

**Comment by Fjfjrixi** [comment]
Reply please

**Comment by Vikassm73** [comment]
MX , Hotstar not possible. Already there in zee5 at few places. I will try to add at more.

**Comment by Fjfjrixi** [comment]
> MX , Hotstar not possible. Already there in zee5 at few places. I will try to add this option at more places in the next version.

Okk 😊 one last request create new addons dagal play for watching old episodes of dangal tv shows not m3u link

**Comment by Vikassm73** [comment]
I will not working on new add-ons

**Comment by Fjfjrixi** [comment]
> I may not be working on new add-ons

Okk i have one last question for u jio tv add on not working again and again i have to update again and again why are u not add jio tv in your repository  ?

**Comment by Vikassm73** [comment]
I am not working on Jio TV so can't add other's work in my repo

**Comment by Fjfjrixi** [comment]
> I am not working on Jio TV so can't add other's work in my repo

Okk

**Comment by Fjfjrixi** [comment]
> I am not working on Jio TV so can't add other's work in my repo

Are u work on new addons in future ?

**Comment by Vikassm73** [comment]
At this point, No

**Comment by Fjfjrixi** [comment]
> At this point, No

Okk

**Comment by Fjfjrixi** [comment]
Hotstar search option are not working when i search any tv series then hotstar show error i face many problems to find any hotstar series please fix this problem
