### ISSUE TITLE
Login zee5

### ISSUE THREAD

**Issue by nabakumarchow** [Vikassm73/AjaykRepo#238]
How to login using otp in zee5 addon

**Comment by Vikassm73** [comment]
There is auto login feature in zee5. Make sure, you have entered proper mobile number in the settings, Press Clear Log. After that try to enter in any option, it is ask OTP.

**Comment by Vikassm73** [comment]
Sorry, it's "Clear Cache". Start zee5 and press "Clear Cache", which is at bottom of the list.

**Comment by nabakumarchow** [comment]
After cleaning cache showing check the log information

**Comment by Vikassm73** [comment]
There might be an error information before "Check the log info". Send me a debug log as mention above.

**Comment by SaiKiranCruzz** [comment]
![16961486101863352085871016201030](https://github.com/Vikassm73/AjaykRepo/assets/84628918/eef1bb6d-8832-4ab2-a496-5ef2ac6b4ba7)
I have this issue since a week and same issue with jio cinema also

**Comment by sayyedmohseen** [comment]
using linux mint latest version and updated kodi. stuck on this page
![Screenshot from 2023-10-04 14-06-20](https://github.com/Vikassm73/AjaykRepo/assets/146930632/53d0c923-7021-4381-a93b-cba49bdca619)

**Comment by Vikassm73** [comment]
will you download latest zee5try below zip

[plugin.video.zee5-2.1.23.zip](https://github.com/Vikassm73/AjaykRepo/files/12801394/plugin.video.zee5-2.1.23.zip)

**Comment by sayyedmohseen** [comment]
It worked with the above zip thanks :)
