### ISSUE TITLE
Jiocinema not working after last update

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [Vikassm73/AjaykRepo#239]
I got notification that Jio cinema update is available and after update, it keeps giving me issues. I haven't checked logs yet and will try to post them soon. But this has happened after latest update of addon.

**Comment by Lovedeep96** [comment]
@Vikassm73 sir please look into this.
I'm also facing this issue.

**Comment by iamnewtogithubhelpme** [comment]
![image](https://github.com/Vikassm73/AjaykRepo/assets/85625460/00f53d90-d807-413c-a9ef-4824eeb149d7)


Log updated where the error is showing.

**Comment by SaiKiranCruzz** [comment]
Same issue brother

**Comment by iamnewtogithubhelpme** [comment]
@Vikassm73 Would sincerely appreciate if you can check on this.

**Comment by Vikassm73** [comment]
Let me know which version of Kodi are you  using? I know there is an issue at some places but it is working at section TV Shows - Fresh Episodes.

**Comment by SaiKiranCruzz** [comment]
Im using 19.5 version kodi now it not working a week ago it was working flawlessly but now not yet working

**Comment by Vikassm73** [comment]
Ok, I will rollback and make it working for kodi 19 also.

**Comment by Vikassm73** [comment]
New version updated
