### ISSUE TITLE
Hi, iam getting ‘ bool object is not iterable in jio tv when opening channels 

### ISSUE THREAD

**Issue by nithinbhandary** [Vikassm73/AjaykRepo#240]

**Comment by technofreak24** [comment]
> @nithinbhandary  

JioTV is working great as of 30 Sep, 2023 at 11:00 AM. **You have to Logout and Login again to solve the error message*** `bool object is not iterable` in JioTV when playing channels as per the Discord KODI Addons Troubleshooting Guide.

**Comment by technofreak24** [comment]
@nithinbhandary JioTV is working great as of 30 Sep, 2023 at 11:52 AM. 
**You have to Logout and Login again to solve the error message** `bool object is not iterable` in JioTV when playing channels.
Screenshots below:
![ss2_115905](https://github.com/Vikassm73/AjaykRepo/assets/121749085/bb2b93cd-647e-4e21-b196-be463e2c7b55)
![ss1_115909](https://github.com/Vikassm73/AjaykRepo/assets/121749085/7b8ef548-ed8a-4a6d-a6b9-756aa86908cd)
![ss3_115856](https://github.com/Vikassm73/AjaykRepo/assets/121749085/d4bd8479-b6b2-4c63-97e9-494c01ef4ef3)

**Comment by nithinbhandary** [comment]
getting same error

**Comment by nithinbhandary** [comment]
![Uploading IMG_1931.jpeg…]()

**Comment by technofreak24** [comment]
> @nithinbhandary getting same error

Which repo & version of JioTV addon are you using? Try re-install of the addon.
Use either [**krreet Releases**](https://github.com/krreet/plugin.video.jiotv/releases) or [**TobAlan Releases**](https://github.com/tobalan/plugin.video.jiotv/releases)

**Comment by Vikassm73** [comment]
For Jio TV follow below repo and put your query there only.

https://github.com/krreet/plugin.video.jiotv
