### ISSUE TITLE
How to play videos in hotstar and zee 5

### ISSUE THREAD

**Issue by Taserwebs** [Vikassm73/AjaykRepo#250]
I have installed the repository and then installed hotstar and zee 5 addons but I can't play videos in it, please give an step by step information as I am an new, it will be helpful, thanks in advance

**Comment by Vikassm73** [comment]
Don't understand what problem you are facing. Are you able to see various list in add-ons? are you getting any error? Send me a screen shot

**Comment by Taserwebs** [comment]
![Screenshot (31)](https://github.com/Vikassm73/AjaykRepo/assets/118518683/95b5340d-1630-4e09-a0bc-cd55f55ccb02)
i cant play live tv on hotstar

![Uploading Screenshot (32).png…]()
like this is there any way to load the channels from hotstar and zee 5 in the guide and channels menu?, or i should go to addons and open it?

**Comment by Vikassm73** [comment]
You have to open it from addon only not available in TV section. For live TV, Unfortunately I don't have valid subscription to test it.

**Comment by Taserwebs** [comment]
Ok thanks for the help
