### ISSUE TITLE
Hotstar issue 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#258]
If u r not able to update this add on please discontinue this add on and create a fresh hotstar add on

**Comment by Fjfjrixi** [comment]
Reply please

**Comment by Fjfjrixi** [comment]
Reply

**Comment by Fjfjrixi** [comment]
Reply me

**Comment by Vikassm73** [comment]
Not thought about this yet.

**Comment by Fjfjrixi** [comment]
> Not thought about this yet.

Please thought
