### ISSUE TITLE
Jio cinema black screen issue 

### ISSUE THREAD

**Issue by Fjfjrixi** [Vikassm73/AjaykRepo#259]
I was using jio cinema add on working perfectly after 4 - 5 days i open this add on showing blackscreen i reinstalled this add on some time this add on working perfectly but after 1 week this this add on showing black screen again please solve this problem

**Comment by Vikassm73** [comment]
I am using this addon continuously but don't face any issue. Instead of uninstall, try logout from setting and play again.
