### ISSUE TITLE
𝗨𝗿𝗴𝗲𝗻𝘁 𝗽𝗿𝗼𝗯𝗹𝗲𝗺 .𝗶𝘀𝘀𝘂𝗲 𝗶𝗻 𝗦𝗼𝗻𝘆𝗹𝗶𝘃 & 𝗛𝗼𝘁𝘀𝘁𝗮𝗿 𝗽𝗹𝗲𝗮𝘀𝗲 𝗳𝗶𝘅

### ISSUE THREAD

**Issue by Bhai2210** [Vikassm73/AjaykRepo#289]
𝗨𝗿𝗴𝗲𝗻𝘁 𝗽𝗿𝗼𝗯𝗹𝗲𝗺 .𝗶𝘀𝘀𝘂𝗲 𝗶𝗻 𝗦𝗼𝗻𝘆𝗹𝗶𝘃 & 𝗛𝗼𝘁𝘀𝘁𝗮𝗿 𝗽𝗹𝗲𝗮𝘀𝗲 𝗳𝗶𝘅... all addons are going day by day ...what is the main issue ..can u explain please ..no one can helping in this issue ..i dont have any cabel in my tv ...i m using your addons since many years before..to watch all seriel ..please help and fix soon

**Comment by Fjfjrixi** [comment]
Download mod apps in phone and cast all series on tv i also doing this

**Comment by Vikassm73** [comment]
Soniliv is working fine. Let me know if you have any specific issue

**Comment by ranjeets9** [comment]
> Soniliv is working fine. Let me know if you have any specific issue

I am installing the addon sonliv is failing with the below 

![image](https://github.com/user-attachments/assets/ad28c8d5-7dcf-4947-97ee-4d294ee0c53e)

**Comment by ranjeets9** [comment]
> > Soniliv is working fine. Let me know if you have any specific issue
> 
> I am installing the addon sonliv is failing with the below
> 
> ![image](https://private-user-images.githubusercontent.com/123510532/360069921-ad28c8d5-7dcf-4947-97ee-4d294ee0c53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjg0NjAsIm5iZiI6MTcyNDI2ODE2MCwicGF0aCI6Ii8xMjM1MTA1MzIvMzYwMDY5OTIxLWFkMjhjOGQ1LTdkY2YtNDk0Ny05N2VlLTRkMjk0ZWUwYzUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxOTIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjBmYjVmNWI4ZmU4ZDJiMTMxZDQyMmQ0ODEyMWZhZTU0OGE0MGM5OGI0NGQ5NmZmNGU1Mzk3NjRkYzVjYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BVl0sHsOtuKLAhlZ7Gz0kIBmVcvWLDSeOVVUnneDO1o)

@Vikassm73 bro any help / guidance here pls

**Comment by ranjeets9** [comment]
> > > Soniliv is working fine. Let me know if you have any specific issue
> > 
> > 
> > I am installing the addon sonliv is failing with the below
> > ![image](https://private-user-images.githubusercontent.com/123510532/360069921-ad28c8d5-7dcf-4947-97ee-4d294ee0c53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjg0NjAsIm5iZiI6MTcyNDI2ODE2MCwicGF0aCI6Ii8xMjM1MTA1MzIvMzYwMDY5OTIxLWFkMjhjOGQ1LTdkY2YtNDk0Ny05N2VlLTRkMjk0ZWUwYzUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxOTIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjBmYjVmNWI4ZmU4ZDJiMTMxZDQyMmQ0ODEyMWZhZTU0OGE0MGM5OGI0NGQ5NmZmNGU1Mzk3NjRkYzVjYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BVl0sHsOtuKLAhlZ7Gz0kIBmVcvWLDSeOVVUnneDO1o)
> 
> @Vikassm73 bro any help / guidance here pls

@Vikassm73 any update here bro??

**Comment by ranjeets9** [comment]
> > > > Soniliv is working fine. Let me know if you have any specific issue
> > > 
> > > 
> > > I am installing the addon sonliv is failing with the below
> > > ![image](https://private-user-images.githubusercontent.com/123510532/360069921-ad28c8d5-7dcf-4947-97ee-4d294ee0c53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjg0NjAsIm5iZiI6MTcyNDI2ODE2MCwicGF0aCI6Ii8xMjM1MTA1MzIvMzYwMDY5OTIxLWFkMjhjOGQ1LTdkY2YtNDk0Ny05N2VlLTRkMjk0ZWUwYzUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxOTIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjBmYjVmNWI4ZmU4ZDJiMTMxZDQyMmQ0ODEyMWZhZTU0OGE0MGM5OGI0NGQ5NmZmNGU1Mzk3NjRkYzVjYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BVl0sHsOtuKLAhlZ7Gz0kIBmVcvWLDSeOVVUnneDO1o)
> > 
> > 
> > @Vikassm73 bro any help / guidance here pls
> 
> @Vikassm73 any update here bro??

@Vikassm73 ??

**Comment by Vikassm73** [comment]
Manually download and install if it is not working from repository

**Comment by ranjeets9** [comment]
> Manually download and install if it is not working from repository

@Vikassm73 oh bro did not know it works this way as well thanks 

![image](https://github.com/user-attachments/assets/a7293ea9-0513-4264-867b-878ca732bd62)

**Comment by ranjeets9** [comment]
@Vikassm73 can u get the hotstar working by any chance?

**Comment by Bhai2210** [comment]
All are working currently except hotstar ...ple
