### ISSUE TITLE
Request for source codes

### ISSUE THREAD

**Issue by ForceGT** [Vikassm73/AjaykRepo#3]
Hey can you please point out where the source code of the various addons described here could be?

**Comment by Vikassm73** [comment]
You will find source code once you install the addon under windows or Linux. Probably under windows, you will find it in the path "C:\Users\Admin\AppData\Roaming\Kodi\addons"

You need to do a further study about this.

**Comment by ForceGT** [comment]
Hey No, what I meant is why have you put zip files on github?
You should put your original unzipped code in a directory structure so that it is easier to read I feel

**Comment by Vikassm73** [comment]
For the auto-update addon, we need to upload this way.
