### ISSUE TITLE
Better instructions to use the plugin

### ISSUE THREAD

**Issue by mountcleverest** [Vikassm73/AjaykRepo#37]
Unable to add the plugin. More instructions would be much appreciated

**Comment by Vikassm73** [comment]
Don't understand what problem you face. You first learn how to install repository in kodi and how to add video addon using google.

**Comment by mountcleverest** [comment]
so i tried adding this github repo link to kodi, it wouldn't find the addon... i gave it diff paths including the exact path to the zipfile itself... 
then i tried a diff approach and loaded the zip file onto my device manually and selected the install addon from zipfile option. this does seem to work, but after installation it doesn't really give me any option to use the addon. if i go to the "my addons" section, i see it there, but opening it just shows me this. not sure how to watch any content. As you can see "Run" is disabled. 

I presumed I am doing something wrong since i am not very experienced with kodi. I have only installed the crew addon prior to this and tried following the same steps
![IMG_4597](https://user-images.githubusercontent.com/32516724/134860229-e98ccf87-8b1d-4ad1-b36b-d7c9da757a99.jpg)
.

**Comment by mountcleverest** [comment]
is there another step after this to add the it as a video add on?

**Comment by Vikassm73** [comment]
You have installed repository. Select Install from Repository option.

**Comment by mountcleverest** [comment]
ah got it installed now. thanks.
