### ISSUE TITLE
Not able to login to Voot

### ISSUE THREAD

**Issue by Aithal88** [Vikassm73/AjaykRepo#4]
![Screenshot from 2021-03-31 18-36-10](https://user-images.githubusercontent.com/81692646/113148875-0262cb00-9250-11eb-8603-781ce51c188c.png)

Voot addon version:- 2.0.1
Kodi Version:- 18.7
Hardware:- Raspberry pi 3
OS:- Raspbian

**Comment by Vikassm73** [comment]
Please check now

**Comment by Aithal88** [comment]
Thanks for looking into this. I'm able to login now. But not able to play any contents. I have attached the error I see.
![Screenshot from 2021-04-07 18-56-59](https://user-images.githubusercontent.com/81692646/113874369-5da63780-97d3-11eb-8b81-7343c8ff62c5.png)

**Comment by Vikassm73** [comment]
Don't have a premium login so can't do proper testing. Anyway, done few corrections, please update the addon and check again

**Comment by Aithal88** [comment]
Tested with updated code. Still observing the attached issue.
![Screenshot from 2021-04-07 22-36-05](https://user-images.githubusercontent.com/81692646/113906368-cd2b1f80-97f1-11eb-9acd-cba8b9a5e6ce.png)

**Comment by Aithal88** [comment]
And another error reported in line 740
![Screenshot from 2021-04-07 22-44-52](https://user-images.githubusercontent.com/81692646/113907398-f0a29a00-97f2-11eb-8b8e-3f8c41b733e0.png)

**Comment by Vikassm73** [comment]
again uploaded with correction

**Comment by Vikassm73** [comment]
Please check again

**Comment by Aithal88** [comment]
errors now in urlencode
![Screenshot from 2021-04-08 15-34-33](https://user-images.githubusercontent.com/81692646/114008581-027e4e80-9880-11eb-8dae-8cfe4080ddbb.png)

**Comment by Vikassm73** [comment]
try now

**Comment by Aithal88** [comment]
Super. It is working now. Thanks a lot.

**Comment by Aithal88** [comment]
Few contents/videos will just pop up and never play. This issue was there even before this URL issue and it is still there.
![Screenshot from 2021-04-08 22-02-54](https://user-images.githubusercontent.com/81692646/114063452-3e340b00-98b6-11eb-8227-dea27bbecd3d.png)

So some videos fail to play with the attached error.

**Comment by Vikassm73** [comment]
it is difficult to trace out this error without valid logins

**Comment by Aithal88** [comment]
Thanks again for fixing the URL issue.Can manage with few videos not playing.
