### ISSUE TITLE
How to add these addons

### ISSUE THREAD

**Issue by puneethbh1984** [Vikassm73/AjaykRepo#47]
Hi,
Can you let me know steps for adding these addons in kodu?

**Comment by Vikassm73** [comment]
First you need to download repo from below link
https://github.com/Vikassm73/AjaykRepo/blob/main/Zips/repository.ajayk-1.1.zip
and install it using zip option.

**Comment by Vikassm73** [comment]
Once you installed AjayK repository, select Install from Repository option. Choose Ajayk Repo, Next video addon and from that install addon of your coice.
