### ISSUE TITLE
SonyLIV  - Login option

### ISSUE THREAD

**Issue by titusrdx** [Vikassm73/AjaykRepo#49]
Sonyliv plugin asks for subscription to view content but no option to login in plugin . Can you fix this ?

**Comment by Vikassm73** [comment]
Email login with password is not available. Otp login is difficult to implement hence not done.

**Comment by xtreamjava** [comment]
So, Sonyliv can't play anything that requires subscription?

**Comment by Vikassm73** [comment]
Yes
