### ISSUE TITLE
ZEE5 : UPDATE LIVE TV SECTION

### ISSUE THREAD

**Issue by TonyStark-guy** [Vikassm73/AjaykRepo#51]
The live tv section of zee5 addon is outdated. Many newer channels have arrived like - Time8, Pratidin Time, ND24, News Time Assam etc. which are free to stream on zee website. Please make the Zee5 addon automatically load up-to-date channel list  everytime we open (kinda like Mxplayer addon) if possible.

**Comment by Vikassm73** [comment]
Please check in new version. Check language in settings
