### ISSUE TITLE
can you update this in zee5

### ISSUE THREAD

**Issue by jsuyog2** [Vikassm73/AjaykRepo#53]
change in `def login()` to mobile no login
```
Pattern = re.compile("[7-9][0-9]{9}")
    if (Pattern.match(addon.getSetting('email'))):
        url = "https://whapi.zee5.com/v1/user/loginMobile_v2.php"
    else :
        url = "https://whapi.zee5.com/v1/user/loginemail_v2.php"
    email=addon.getSetting('email')
    password = addon.getSetting('password')
    if email:
        if (Pattern.match(addon.getSetting('email'))):
            body = {"aid":"91955485578","guest_token":"48b30b9e-b677-4669-a079-5edc36bf54f9","lotame_cookie_id":"","mobile":"91"+email,"password":password,"platform":"web","version":"2.50.87"}
        else :
            body = {"aid":"91955485578","guest_token":"48b30b9e-b677-4669-a079-5edc36bf54f9","lotame_cookie_id":"", "email":email,"password":password,"platform": "web","version": "2.50.50"}
```
change in `def get_user()` to mobile no login

```
Pattern = re.compile("[7-9][0-9]{9}")
        if (Pattern.match(addon.getSetting('email'))):
            headers.update({'mobile': data['mobile']})
        else:
            headers.update({'email': data['email']})
```

insert in def play_live(item_id)
change url to https://spapi.zee5.com/singlePlayback/getDetails/secure
`headers.update({'Content-Type': 'application/json'})`

**Comment by jsuyog2** [comment]
Still Movies not working in zee5

**Comment by Vikassm73** [comment]
Updated. Please check and confirm new version. Live TV should work

**Comment by jsuyog2** [comment]
1. comment web_pdb.set_trace() - line no 157
2. device_id change to "WebBrowser"

**Comment by Vikassm73** [comment]
Yes, Noticed web_pdb error latter. Now updated.

device_id =WebBrowser does not work now hence used proper deviceid

**Comment by jsuyog2** [comment]
actually, your device_id is not working in my system so I change to WebBrowser and it's working properly

**Comment by Vikassm73** [comment]
Are you using zee5 login? If yes, does premium live channels are working ?

**Comment by jsuyog2** [comment]
Yes I have Zee5 Premium and Premium Live channels working fine

**Comment by Vikassm73** [comment]
Noticed that device ID "WebBrowser" working fine in Matrix but not in Leia.

**Comment by jsuyog2** [comment]
I am using Matrix. device_id is actually in localStorage on the website.

**Comment by Vikassm73** [comment]
Actually, I did not get url to fetch dynamic device ID hence used fix one which may not work on other device.
