### ISSUE TITLE
SonyLiv unable to view content

### ISSUE THREAD

**Issue by fdrgiit** [Vikassm73/AjaykRepo#54]
I am unable to login or view any content with the recent version. Can you please tell me how can I do this.

**Comment by Galaxysanty** [comment]
I am also unable to see any content through Kodi. In the video add on under Add on repository, the error says The dependency on script module six version 0.0.0 could not be satisfied.

**Comment by Vikassm73** [comment]
search for script.module.kodi-six and download and install it for your kodi version

**Comment by Vikassm73** [comment]
Login feature is not added (As it required OTP). Any episodes which are working without logins should work.

**Comment by fdrgiit** [comment]
@Vikassm73 Can you please tell me which episodes/movies work?
I tried couple of SabTV shows...and nothing worked for me. Hence asked this.
Thanks,

**Comment by Vikassm73** [comment]
All are working except some premium content like web series. Tested Tarak Mehata..,Wagle ki Duniya..

All are working..
