### ISSUE TITLE
Started receiving this error after updating zee5 to 2.1.8

### ISSUE THREAD

**Issue by adityapv** [Vikassm73/AjaykRepo#55]
![IMG_20220209_104930.jpg](https://user-images.githubusercontent.com/16288697/153126805-de571db3-de95-48dd-847d-219cb27d3c3c.jpg)

Device: Xiaomi MiTV 4A
Kodi Version: Matrix 19.3
Operating System: Android 9

After clearing cache, resolver cache, removing Kodi from memory and reinstalling zee5 plugin, I am receiving this error:

![IMG_20220209_111611.jpg](https://user-images.githubusercontent.com/16288697/153129550-ab75ed1b-b56b-48f2-945d-ef0e5b5bc69a.jpg)

**Comment by Vikassm73** [comment]
If you are playing premium video, you will get this error. Try playing non premium content or live channels

**Comment by adityapv** [comment]
I have only played non-premium news channels like ABP News, DD News but still it threw this error.

**Comment by Vikassm73** [comment]
Try previous version 2.1.7.
