### ISSUE TITLE
ZEE5 Not working on Kodi

### ISSUE THREAD

**Issue by ganesh-user** [Vikassm73/AjaykRepo#56]
H96 Android Box,
Kodi Version- 19.3
PVR IPTV Simple Client Version 19.1.0 Installed
Installed repository.ajayk-1.1
Max Player - Working
Sony Liv - Working
ZEE5 - Not Working, 
Instead getting error "One or More Items Failed to Play. Check the log for more information about this message." Please see attached error and log screenshots.
![Untitled](https://user-images.githubusercontent.com/99388090/153391567-3b1f63b1-3c26-44ff-97a7-4e27a64f4d39.jpg)
@Vikassm73 @nikhilk0

**Comment by ganesh-user** [comment]
@Vikassm73 Any solution ?

**Comment by Vikassm73** [comment]
If you can get Chrome browser developer mode on Android, you can find the device ID. Then you can fix it in  the code. It's a difficult process, but it can be achieved.

**Comment by Vikassm73** [comment]
Try new update. Various Device ID selection is given in setting. Try this.

**Comment by ganesh-user** [comment]
I updated ZEE5 to version 2.1.9. Found 4 device IDs in setting. Out of this four device ID, D3 worked for me.  Awesome. Thank you for the update. You may close this issue.
