### ISSUE TITLE
Zee5 Activation issue

### ISSUE THREAD

**Issue by samitray-at-consultree** [Vikassm73/AjaykRepo#59]
How can I activate Zee5 using my subscription so that I can view all the premium content. Currently I can't watch the live channels like Zee Cinema HD

**Comment by Vikassm73** [comment]
Are you able to play other content? Please try to use various device Id from setting. Using any one, you should able to play live channels. (In my case, I was able to play using D3)

**Comment by sk0103** [comment]
I have tried with all device ID, but zee5 is not working. I get an error that the device id is incorrect/invalid.

**Comment by Vikassm73** [comment]
Try with new update.
