### ISSUE TITLE
Zee5 - Device ID invalid/incorrect

### ISSUE THREAD

**Issue by sk0103** [Vikassm73/AjaykRepo#61]
Hey, 

Thanks for your awesome work.

I have device id issue where I cannot load any live tv channels on zee5.

I tried changing device id to all the 4 options.

But it did not work.

Your help will be appreciated.

**Comment by AbhayF8** [comment]
are you talking about premium live TV channels?

**Comment by sk0103** [comment]
I'm not sure if Zee Marathi HD is premium live tv channel.

I only use this channel on zee5.

**Comment by AbhayF8** [comment]
it should be a premium channel because only news channel work for free and other channels show subscription or purchase couldn't be found 

you should watch zee marathi in jio tv from BotAllen's repo if you have a jio sim https://botallen.com/blog/jiotv-kodi-add-on

**Comment by sk0103** [comment]
Jiotv only offer SD version of Zee Marathi.


Is their any other way to watch HD version.

Will this be fixed in upcoming updates.

Thanks for replying.

**Comment by Vikassm73** [comment]
Are you working on Android device?

**Comment by sk0103** [comment]
Working on Android device?

I did not understand this phrase.

I was not using the Android device, when trying to play the channel on TV.

**Comment by Vikassm73** [comment]
I mean is Kodi installed on Android device, May be Android box or TV? Mostly facing problem in android device where I was unable to get proper device ID

**Comment by sk0103** [comment]
I installed it on Android TV.

**Comment by Vikassm73** [comment]
In the android device, it is difficult to get browser in the Development Mode. If you able to do that, we can find out Device ID using browser and can be fix it in this addon.

**Comment by sk0103** [comment]
https://play.google.com/store/apps/details?id=web.dassem.websiteanalyzer

Found this app, I'm not sure if this is useful.

**Comment by Vikassm73** [comment]
No, this is not helpful. If you compare it with chrome under windows, it will show only elements tab. We need Network or Application tab info.

**Comment by sk0103** [comment]
Is their any extension which can be used on kiwi browser for this purpose?

**Comment by Vikassm73** [comment]
Device ID option D1 should work in your case.

In Kiwi browser, Click on Developer Tools setting. Go on second screen. Select Application tab there you will find "guestToken". 
which is device ID. 

![Zee5](https://user-images.githubusercontent.com/41675437/159419187-e4c1a662-7047-42ed-895a-d7955e509883.jpg)

**Comment by sk0103** [comment]
But device id is alphanumeric here. How do I know which device ID to use.

Does device ID follow the number of devices  on which zee5 is logged in?

**Comment by Vikassm73** [comment]
There will be only one guest token. Format may be like "abcefca6-94cf-4154-b81d-321116b8c7fb" or "o7JvbEPk3KRA14d8FwEr000000000000". It will be different on various device though in some cases same ID can work on multiple devices.

Send your device ID to me and your personal email ID. I will send zip file for testing. If this work then I will give option to add device ID manually.

**Comment by sk0103** [comment]
Can we connect over telegram.

Do i have to do this on Android TV, I mean to install kiwi browser on TV and get the Device id from there.

Telegram: @sk1920

**Comment by Vikassm73** [comment]
Yes, you have to do it on Android TV.

**Comment by sk0103** [comment]
I have sent the email. 

Please check spam folder as well.

**Comment by Vikassm73** [comment]
Share complete device ID first to create file

**Comment by sk0103** [comment]
I have added the device id in email.

**Comment by Vikassm73** [comment]
No problem, I have added option to enter device Id manually in setting. File send. Please check and confirm

**Comment by sk0103** [comment]
Do i have to uninstall previous plugin?

**Comment by sk0103** [comment]
Followed the steps, added device id manually. But it did not work.

I tried changing to all 4 device ID too. But that too did not work.

I think we have to remove device id selection as we are entering device id manually.

**Comment by Vikassm73** [comment]
If you enter device ID manually, it will consider that otherwise it will pickup from selection. Yes you have to enter complete device ID. Device ID is case sensitive.

**Comment by sk0103** [comment]
I did enter complete device id of 32 characters![IMG-20220322-WA0002.jpg](https://user-images.githubusercontent.com/47568823/159624328-88a6f99c-fc13-4dcb-84e8-98d6f9fb7665.jpg)

**Comment by Vikassm73** [comment]
In your case it is 36 character. (Including "-" character)

**Comment by sk0103** [comment]
Yes, including - 

I added all these in Kodi.

**Comment by Vikassm73** [comment]
Without entering login details, are you able to play free content?

**Comment by sk0103** [comment]
I have login credentials added, and I'm able to play free content.

**Comment by sk0103** [comment]
Then why does it not play premium content.

**Comment by Vikassm73** [comment]
Premium content have "Widevine license acquisition issue" as those content are highly encrypted which currently can not be decrypted by Kodi / Inputstream Adaptive.

**Comment by Vikassm73** [comment]
Check this new version 2.1.12. Premium content should work under Linux / Android. It will not work under windows because of VMP issue.

**Comment by sk0103** [comment]
Working now.

Thanks

**Comment by sk0103** [comment]
I was able to play premium channel by changing device ID to D3, i did not add device ID manually.

**Comment by Vikassm73** [comment]
> 

Try various device combination. If did not work then find out device ID using method mentioned in this post and enter it manually.

**Comment by Vikassm73** [comment]
> 

Try various device combination. If did not work then find out device ID using method mentioned in this post (Initially, you can use device ID from your laptop. If not work then get it from actual one - May be your Android TV) and enter it manually.

**Comment by shri1990** [comment]
but in my case v2.1.11 works better, atleast the premium tv shows works fine with device id D1.. in the v2.1.12 its not working..
getting the guestToken in the kiwi browser android tv version is quite difficult..
is it possible to log the device id in the kodi.log atleast we can get it from there and enter manually?

**Comment by Vikassm73** [comment]
You can ask zee customer care to clear all device log. Once done, again try with this application

**Comment by shri1990** [comment]
its working now, i manually entered the token id.. Thanks

**Comment by Vikassm73** [comment]
Try following

1. Do "clear Cache" in zee5 and try again
2. If step 1 doesn't work, log out of your browser (if it says you're already logged in) and login again. It may ask for to clear device (Only if number of devices are full). Do it and use device id from that machine and check again.
