### ISSUE TITLE
Sony LIV 

### ISSUE THREAD

**Issue by sunnyanta1989** [Vikassm73/AjaykRepo#62]
Sony LIV installation getting cancelled on 64%

**Comment by sunnyanta1989** [comment]
This same thing is happening on my Android TV Box as well as on Windows PC.

**Comment by Vikassm73** [comment]
try now

**Comment by sunnyanta1989** [comment]
Installed but on clicking on "TV Shows" an error message comes "SonyLIV Error".
It never happend in the previous installations
