### ISSUE TITLE
Request to new addon

### ISSUE THREAD

**Issue by anbusaga** [Vikassm73/AjaykRepo#66]
Hello bro

Required addon for the app(visit app store for the apps)

sun nxt (https://www.sunnxt.com/)
VI movies and TV (https://vimoviesandtv.in/)

Can you create addon for the above apps please...

**Comment by adityapv** [comment]
Hi @Vikassm73, you have done a great job in creating Addons for voot, zee5, sonyliv and mxplayer. Thanks a lot for all the work you have put into creating and maintaining these addons, we really appreciate it.
I have a gentle request for a new addon if you have the time and energy to allocate the same. The addon is for Vi Movies and TV. Botallen used to maintain Jiotv addon but now it seems he has deprecated the addon. It would be of great help for us users of your addons if you consider this request and hopefully be able to work on it.

**Comment by Vikassm73** [comment]
Vi Movies and TV need paid subscription. I only do work for those who also provide it for free.
