### ISSUE TITLE
Sonyliv

### ISSUE THREAD

**Issue by Taburientelp1** [Vikassm73/AjaykRepo#7]
Hi thanks for the Update, just wanted to ask if for Sonylive Addon do you need VPN ? cause its not working  .... and is it possible to use it just by enabling indian IP address ?  thanks a lot for your work

**Comment by Vikassm73** [comment]
Actually, not tested outside India. If sonylliv.com works perfectly using VPN then this addon will also work.

**Comment by Taburientelp1** [comment]
is there any way to add the option ip address configuration like in voot i think that should work smooth  with sonylive

**Comment by Vikassm73** [comment]
I think Voot is not geo-restricted hence working without VPN. Just check voot.com in the browser without VPN.

**Comment by Taburientelp1** [comment]
it is geo-restricted  it just appears with a blank page not found

**Comment by Taburientelp1** [comment]
in kodi when i added the indian IP it works perfectly without a vpn

**Comment by Vikassm73** [comment]
If you keep the Indian IP address blank in Voot, does it work?

**Comment by Taburientelp1** [comment]
at least here in Spain  if i keep it blank it doesn't work

**Comment by nikhilk0** [comment]
Sorry for hijacking this thread, but I think SonyLiv addon is not compatible with Matrix yet. I haven't looked at the code fully but StringIO, BaseHTTPServer which are used in the addon are deprecated in python 3. Also, I haven't tested the addon in Leia as I don't currently have any Leia fork setup.
@Taburientelp1 are you on Matrix?
@Vikassm73 can you make the addon Matrix compatible in the upcoming releases?

**Comment by Vikassm73** [comment]
correction done for matrix

**Comment by nikhilk0** [comment]
The addon is still not functional. You missed correcting 'SocketServer' for matrix compatibility. So, I had to change 'SocketServer' to 'socketserver' to get the main options. But after that almost nothing works:

- I'm not able to get past most of the listings in Channels section and None of the listings in Movies section
- For the shows which I managed to get past through to the episodes, the videos don't play.

Hope you're able to fix those issues.

**Comment by Taburientelp1** [comment]
Sorry been using leia since still lot of addons are not compatible 19.0

**Comment by Vikassm73** [comment]
The correction did for socketserver. Version not changed so you will have to manually update.

**Comment by nikhilk0** [comment]
> The correction did for socketserver. Version not changed so you will have to manually update.

Menus are now accessible, but the issues mentioned in my previous comment are still there.

**Comment by Vikassm73** [comment]
I don't have a matrix version. So please share the log

**Comment by nikhilk0** [comment]
Thanks for letting me know. I'm attaching logs for matrix here.
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/6493155/kodi.log)
I also tried the addon on leia setup. On leia movies sub-sections are accessible but still can't play any movies and episodes. The error while playing is the same on both matrix and leia. Tell me if you want logs for leia as well.

> Sorry been using leia since still lot of addons are not compatible 19.0

Most of the addons which I use are available on Matrix now. But that was not the case in the 1st month of the release of Matrix. So I understand.

**Comment by Vikassm73** [comment]
In your case local proxy is not working. Just try to comment line 744 and 745 and try to play working stream.

**Comment by nikhilk0** [comment]
Just to confirm these are lines which I commented
![image](https://user-images.githubusercontent.com/45728234/118610086-0aaf9f00-b7d9-11eb-997f-727d77b62141.png)
But after that I'm getting following error
![image](https://user-images.githubusercontent.com/45728234/118610220-29159a80-b7d9-11eb-960d-6c55acb795bf.png)

**Comment by Vikassm73** [comment]
Done few changes. Please check now

**Comment by nikhilk0** [comment]
Still 403
![image](https://user-images.githubusercontent.com/45728234/118790574-867e1a00-b8b3-11eb-82a2-ed1e9716092e.png)

**Comment by Vikassm73** [comment]
Don't find any solution. There should not be any issue while using in India. If you are able to play it on sonyliv.com then it should work in this addon also.

**Comment by nikhilk0** [comment]
On the website, login is required. After logging in I'm able to play the videos. But in kodi there is 

> "ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer"

 every time I play any video. 
No worries for me though. I hardly use sonyliv. I was just checking out and testing the addon.

**Comment by Vikassm73** [comment]
The correction did, You can check it now.

**Comment by nikhilk0** [comment]
Just checked and it's working.
