### ISSUE TITLE
Url for reposirory

### ISSUE THREAD

**Issue by ethnik87** [Vikassm73/AjaykRepo#72]
Please create url  for the repository as unable to download direct zip on apple tv 4k Thank you for all your hard work so far

**Comment by Vikassm73** [comment]
https://github.com/Vikassm73/AjaykRepo/raw/main/Zips/repository.ajayk-1.1.zip

**Comment by ethnik87** [comment]
Hi
     Thank you for replying I added this url to the file manager in kod on
apple tv which adds in fine but when trying to install the repo zip it
shows empty I know you are busy if you can suggest something then great if
not I can install on my android tv and not my apple tv
Thank you
Tarun Parekh

**Comment by Vikassm73** [comment]
Noticed that actual path should have "https://github.com/Vikassm73/AjaykRepo/raw/main/Zips/" but that path also not accessible using File Manager. If somehow, you can able to upload this zip to any web site which has FTP access then it should work but currently, if you can able to copy this zip to pen drive and that pen drive get detected in kodi then you can able install.

**Comment by ethnik87** [comment]
Hi
      After reading a few forums I downloaded Google drive on kodi and
logged in I uploaded ajayk  zip on the app on my phone and opened Google
drive on kodi pressed the file where a pop up appears press download and
choose home folder and tmp folder and press ok then install from zip as
normal and choose  home folder  and top folder zip file will be there.
