### ISSUE TITLE
Improvement: add Linux User Agent in ZEE5

### ISSUE THREAD

**Issue by AbhayF8** [Vikassm73/AjaykRepo#75]
if xbmc.getCondVisibility('System.Platform.Android'):
    USER_AGENT = "Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
elif xbmc.getCondVisibility('System.Platform.Windows'):
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
`elif xbmc.getCondVisibility('System.Platform.Linux'):
    USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36"
headers["user-agent"] = USER_AGENT`

**Comment by Vikassm73** [comment]
Yes, that I noticed yesterday, done correction but not uploaded.

Thanks
