### ISSUE TITLE
Voot App - Shows are missing

### ISSUE THREAD

**Issue by prakharaug** [Vikassm73/AjaykRepo#79]
"The Khatra Khatra Show" is missing in the add on however the same is available on voot.com website.

[https://www.voot.com/shows/listing/watch%20the%20khatra%20khatra%20show?url=content%2Fgeneric%2Fseries-wise-episode_curated%3Fid%3Dinclude%3A1283594%26sort%3Depisode%3Aasc%26responseType%3Dcommon&trayType=dynamic&filterValue=true&&sortValue=Episode%3Aepisode%3Aasc%2Cdesc%3Atrue&cardType=ContentCardRail&trayID=rail_jio_voot-common_100414_0_series-wise-episode_curated_publish04-1](url)

**Comment by Vikassm73** [comment]
Wait for next version

**Comment by Vikassm73** [comment]
New Version uploaded

**Comment by prakharaug** [comment]
Thanks It's working now. But Zee5 is not working now !!

**Comment by Vikassm73** [comment]
Let me know exactly where you are facing problem

**Comment by prakharaug** [comment]
The issue is sorted now.
Checked the logged file and found the following issue

> 022-04-29 18:39:08.926 T:6296    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'inputstreamhelper'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Prakh\AppData\Roaming\Kodi\addons\plugin.video.zee5\main.py", line 3, in <module>
                                                       from resources.lib import plugin
                                                     File "C:\Users\Prakh\AppData\Roaming\Kodi\addons\plugin.video.zee5\resources\lib\plugin.py", line 38, in <module>
                                                       import inputstreamhelper
                                                   ModuleNotFoundError: No module named 'inputstreamhelper'
                                                   -->End of Python script error report<--

So have installed the addon inputstreamhelper manually and the issue is resolved.
