### ISSUE TITLE
SonyLiv

### ISSUE THREAD

**Issue by YeahArun** [Vikassm73/AjaykRepo#8]
While installing the AjayKRepo-Main repository on Kodi 19 Matrix - it says Failed to install add-on from zip file because of an invalid file structure. I believe this is for kidi 18 verion. Will appreciate if you do the tweaking to run it on Kodi 19 Matrix. Thanks...

**Comment by YeahArun** [comment]
just to add - When I extract the repo file and try to install either of the plugins 2.0.x, then it gets installed. I am able to browse different sections but not able to play anything. May be thats because as i didnt login. In setting I done get any option to login. Neither it prompts when I start the Sonyliv add-on. Pls help, Thanks in Advance..

**Comment by YeahArun** [comment]
sorry new to this platform by mistake closed with comment... its still open...

**Comment by Vikassm73** [comment]
You might have used download zip option from code. Instead of that use download zip link given on the main page and install repository.

None of my plugins required login. Install Mxplayer or voot and check the status. Sony has certain issue that I will check.

**Comment by YeahArun** [comment]
I am sorry, coud not find the download zip link on main page. So I had to download from code. Please provide the direct zip link to be downloaded.
Also on AjayK repo, Voot does ask for login, Zee5 is ok.

Vikassm73/Voot - again downloaded from code as no link available, and it says some python 2.24.0 issue when repository is tried to be added.

But thats OK, I am more interested in SonyLiv. If you can help resolving that. Thanks.

**Comment by Vikassm73** [comment]
![image](https://user-images.githubusercontent.com/41675437/120914096-6b841600-c6b9-11eb-9cc0-a787a8b57d71.png)

Here is the link on the main page. I am working on Sonyliv. This works perfectly on Kodi 18 but has an issue with Kodi 19.

**Comment by Vikassm73** [comment]
Correction did, Please check now
