### ISSUE TITLE
Sony LIV Not Working

### ISSUE THREAD

**Issue by shubhamshah02** [Vikassm73/AjaykRepo#81]
Tried to play Tarrak Metha but am getting an error that One or more files failed to play.

[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/8750107/kodi.log)

**Comment by AbhayF8** [comment]
For me it's working but I am not getting audio playback only video. I played latest last 2 episodes of TMKOC and everything was fine except Audio. @shubhamshah02 
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/8750572/kodi.log)

**Comment by Vikassm73** [comment]
Do clear cache. I will ask to enter OTP again after that try to play.

**Comment by Vikassm73** [comment]
Do clear cache. I will ask to enter OTP again after that try to play. If you using it without login, try putting your mobile number in setting.
