### ISSUE TITLE
Zee5 Premium content issue

### ISSUE THREAD

**Issue by adityapv** [Vikassm73/AjaykRepo#83]
Hi,

I recently purchased the subscription of Zee5 using my mobile no., however, when I am trying to open the live channel from my favourites, it is throwing 'Subscription or purchase couldn't be found'. I also tried to access Premium folder but there also I got a Zee5 error check for logs.
![Screenshot_2022-06-01-10-29-51-58_754cf9a4094c34a8eeb04648e2e3eb8d.jpg](https://user-images.githubusercontent.com/16288697/171331331-a6385f2a-ebee-41a9-b418-400766fda022.jpg)

**Comment by Vikassm73** [comment]
Need complete log with debug log as well component log enabled. Upload complete in text format using https://paste.kodi.tv/

**Comment by adityapv** [comment]
Hi,

I have uploaded the log at:
https://paste.kodi.tv/sinunotite.kodi

**Comment by Vikassm73** [comment]
This is normal log. Follow below link to enable debug log and component enabled log. Also please let me know whether non premium content as well as non premium live channels are working fine or not.

https://github.com/Vikassm73/AjaykRepo/issues/73

**Comment by adityapv** [comment]
Hi,

Thanks for sending in the new plugin, I will install and test it. Whenever I keep the login credentials blank and erase cache, I am able to view free channels but once I have entered login credentials, it shows the subscription could not be found.
I will send the latest logs with debug and component logs enabled by today

**Comment by Vikassm73** [comment]
"subscription could not be found" means you might have entered wrong password. and even with wrong password, you should able to play non premium content.

**Comment by adityapv** [comment]
Hi,

I triple checked the password and username, I deliberately entered wrong one time to check if it is throwing any other error or not, when I did it throws Invalid login credentials error.
For username, I am entering my 10-digit mobile number I am not including country code or anything else. Let me know if that's ok.
I am working on generating the required logs, will send it to you by today.

**Comment by Vikassm73** [comment]
yes, 10 digit code should be there without country code. hope you are using this from India only

**Comment by adityapv** [comment]
Yes, I am logging in from India only. Please find the latest log: https://paste.kodi.tv/owodadulog.kodi

**Comment by Vikassm73** [comment]
It shows that you are facing problem while accessing folder. Let me know exactly which path you are following? 
also try playing other folder and confirm

**Comment by adityapv** [comment]
For other premium content also, its the same, Subscription cannot be found issue.
Updated Log: paste.kodi.tv/jugonameta.kodi

I am accessing Live Channels from Live TV -> Premium folder. I also tried to play a channel which through favorites
I have bought the subscription through fleek, applied it on my account using Have a Prepaid Code feature.

**Comment by Vikassm73** [comment]
No link for new log.

**Comment by Vikassm73** [comment]
Have you send log after updating plugins? and done clear cache after that. I did not find required details. Please exit Kodi and start again and after that send me the log

**Comment by adityapv** [comment]
Hi,

Updated Log: https://paste.kodi.tv/ofosetuzog.kodi

This one is generated from my TV, there I have installed the latest zip that you had sent, cleared cache, exited and relaunched Kodi, enabled Debug and Component (libcURL library (HTTP(S), DAV)) logs and visited Live TV -> Premium, News, GEC and then accessed Premium folder at root location, tried playing Attack, Jhund, RRR, still received the error.

**Comment by adityapv** [comment]
![kodi.log.txt](https://github.com/Vikassm73/AjaykRepo/files/8831544/kodi.log.txt)

This is after enabling Debug log from Zee5 plugin. Previously had only enabled Debug log from Kodi.

As file is too large for paste.kodi.tv, attaching here.

**Comment by Vikassm73** [comment]
Debug log inside zee5 plugin is of no use. Your log is good but need additional details to understand better. Please send after updating below. After updating, Exit Kodi. After restart, do Clear log first. Then try to access Premium Live folder. After error try to play any premium movie and send me the log


[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/8831610/plugin.video.zee5.zip)

**Comment by adityapv** [comment]
Hi,

Have you sent any latest zip for me to update? I am not able to see that

**Comment by Vikassm73** [comment]
Link now appears

**Comment by adityapv** [comment]
Hi,

Please find the latest log at: https://paste.kodi.tv/litutopobe.kodi

**Comment by Vikassm73** [comment]
Thanks for the log. Noticed that there is no subscription issue.  It works fine at various places. It only your device giving such problem. try to playing using this new plugin. if failed, install chrome browser at your device and after that try to play. If failed again then nothing can be done.

[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/8842075/plugin.video.zee5.zip)
