### ISSUE TITLE
Device id

### ISSUE THREAD

**Issue by amtabhshk** [Vikassm73/AjaykRepo#84]
While playing any content, it shows invalid device id.
What should be the device id ?

And it should integrate seems lessly to other add-ons like pvr client or any movie or music client

**Comment by amtabhshk** [comment]
Like botallen jio tv

**Comment by Vikassm73** [comment]
Just follow below link

https://github.com/Vikassm73/AjaykRepo/issues/61#issuecomment-1127305648

**Comment by amtabhshk** [comment]
Thanks, even after clearing the cache it's not working. I couldn't find the device id from laptop browser login also.
Can you help me with that.?

Also is there any way to integrate this to other addon to get all video/movies to Kodi movie/videos sections and pvr client for live tv ip?

Without above plugin, searching individually and watching is little inconvenient it seems

**Comment by Vikassm73** [comment]
No, it is not possible to get it directly in Kodi. I have already explained the solution for this kind of issue. Just go through the closed as well open issue related to zee5
