### ISSUE TITLE
Zee5 login Error

### ISSUE THREAD

**Issue by CharuduttPradhan** [Vikassm73/AjaykRepo#85]
I have been trying to log in Zee5 after installation but cannot use it even after entering Userid and password

**Comment by Vikassm73** [comment]
Follow below link. Download zee5 zip and install it manually.

After that send me the debug log (How To  : Read it properly in the link)

https://github.com/Vikassm73/AjaykRepo/issues/83

**Comment by Vikassm73** [comment]
Hope this problem get solved as there is no further reply
