### ISSUE TITLE
Sonyliv is not working 

### ISSUE THREAD

**Issue by kanha636336** [Vikassm73/AjaykRepo#86]
I often get an error massage whenever I try to play any video on sonyliv
I have put a screenshot of error massage please check that out and get it solved as soon as possible 
![Screenshot_2022-06-29-08-17-15-308_org xbmc kodi](https://user-images.githubusercontent.com/86860315/176421921-56cab310-7b03-4716-b1b3-4aee01a3e7a6.jpg)
All the live TV channel or videos are not playing anymore for last night in sonyliv 
Please fix it 🙏

**Comment by Vikassm73** [comment]
Yesterday there was an issue but now, they are working

**Comment by kanha636336** [comment]
Yes, now it's all working fine except (live now)
Sonyliv -> sports -> live now -> stream doesn't work 
![IMG_20220630_220908](https://user-images.githubusercontent.com/86860315/176731668-f8bf1be8-f44e-4d1e-b5d3-c2c13479a892.jpg)
![Screenshot_2022-06-30-22-08-10-886_org xbmc kodi](https://user-images.githubusercontent.com/86860315/176731680-13814d17-106c-48f5-b27b-0d567f440932.jpg)
Please can you fix it 🙏
