### ISSUE TITLE
Again sonyliv live tv is not working bro please give it a permanent fix

### ISSUE THREAD

**Issue by kanha636336** [Vikassm73/AjaykRepo#87]
Live tv in sonyliv is not working sometimes
can you fix it 🙏

**Comment by Vikassm73** [comment]
Correction done. 

There are frequent changes from Sonyliv side. I have to track those and need to do correction. So permanent solution can't possible.

**Comment by kanha636336** [comment]
Okay 👍 thanks for fixing the issue

**Comment by kanha636336** [comment]
Problem got fixed
