### ISSUE TITLE
how to run script

### ISSUE THREAD

**Issue by sirfpsycho** [Vikassm73/AjaykRepo#89]
Hello, I tried to run command  "main.py -h" in mx player script but it says

ModuleNotFoundError: No module named 'xbmc'

I tried to run:
pip install xbmc
ERROR: Could not find a version that satisfies the requirement xbmc (from versions: none)
ERROR: No matching distribution found for xbmc

**Comment by Vikassm73** [comment]
you have to use it from Kodi.

**Comment by sirfpsycho** [comment]
> you have to use it from Kodi.

any tutorial to use kodi? I am using windows computer.

**Comment by Vikassm73** [comment]
Download latest Kodi software from https://kodi.tv/

And Search for "How to Install Repository manually in Kodi"

Also "How to Install Addon" from Repository
