### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by brnwlshubh** [Vikassm73/AjaykRepo#91]
Please include "Colors HD" Hindi in "India.m3u"

**Comment by Vikassm73** [comment]
Added. 
Mostly, I concentrate on News Channels. These entertainment channels,  there streaming link has little life and difficult to find out so I avoid it. For this, I use Voot addon.

**Comment by brnwlshubh** [comment]
Is there any way to convert addon into m3u? @Vikassm73

**Comment by Vikassm73** [comment]
> Is there any way to convert addon into m3u? @Vikassm73

No
