### ISSUE TITLE
Zee5 premium movies not working 

### ISSUE THREAD

**Issue by BadoleMani** [Vikassm73/AjaykRepo#94]
I have zee5 subscription and I had login with all detail that you mentioned. All premium tv channel working but premium movies not working.
Please solve this issue.

**Comment by Vikassm73** [comment]
First do clear log and after re-check the same

If same problem continue then install below addon manually and send me the debug log

[plugin.video.zee5.zip](https://github.com/Vikassm73/AjaykRepo/files/9429738/plugin.video.zee5.zip)

**Comment by BadoleMani** [comment]
[kodi.log](https://github.com/Vikassm73/AjaykRepo/files/9437180/kodi.log)
Here is kodi log

**Comment by Vikassm73** [comment]
This is issue of your android device. This is widevine issue which is unfortunately can not be rectified.
