### ISSUE TITLE
Sony Liv old episode not playing

### ISSUE THREAD

**Issue by ganesh-user** [Vikassm73/AjaykRepo#97]
H96 Android Box,
Kodi Version- 19.3
sonyliv-2.0.13
From last 2-3 days having problem of Sony Liv not playing any old episode. Live TV is OK and playable But not earlier episodes. Attached are log screen shots.
![1](https://user-images.githubusercontent.com/99388090/189271142-8235e9d1-dbb1-4620-95b6-41bd2de13ab9.jpeg)
![2](https://user-images.githubusercontent.com/99388090/189271159-c6422dd2-4601-43f7-b740-014a98eb37f1.jpeg)
![3](https://user-images.githubusercontent.com/99388090/189271183-e3d5c6a7-655d-4258-a918-3b6b2a2faab0.jpeg)

**Comment by Vikassm73** [comment]
Let me know about any specific episode. I will check it

**Comment by ganesh-user** [comment]
I am not using Login Since I am using sony liv without login from long time. And issue started just 2 days before.
Regarding any specific episode - Any earlier episode is not playable, yes Any. But Live TV is ok.

**Comment by Vikassm73** [comment]
You need to put your mobile number whether you subscribed or not. Do clear log, after that it will ask OTP once. enter and try to play.

**Comment by ganesh-user** [comment]
OK, After Login with OTP, the issue resolved. Thank you. You may close this issue now.
Just to inform others. The OTP login is bit Tricky. You have to- 
Sony Liv >options >Login>Mobile. Here you have to enter your mobile No. and click OK. At this point you will NOT receive OTP Nor any place to enter your OTP. You will receive OTP and one box will open to enter OTP, when click to play any content, 
Thanks.
